//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}CHARACTERISTIC_VALUE_CODED" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}CHARACTERISTIC_VALUE_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}CHARACTERISTIC_VALUE_2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "characteristicvaluecoded",
    "codelistid",
    "agency",
    "characteristicvalue1",
    "characteristicvalue2"
})
@XmlRootElement(name = "E1VDEWCAV_3")
public class E1VDEWCAV3 {

    @XmlElement(name = "CHARACTERISTIC_VALUE_CODED")
    protected CHARACTERISTICVALUECODED characteristicvaluecoded;
    @XmlElement(name = "CODE_LIST_ID")
    protected CODELISTID codelistid;
    @XmlElement(name = "AGENCY")
    protected AGENCY agency;
    @XmlElement(name = "CHARACTERISTIC_VALUE_1")
    protected CHARACTERISTICVALUE1 characteristicvalue1;
    @XmlElement(name = "CHARACTERISTIC_VALUE_2")
    protected CHARACTERISTICVALUE2 characteristicvalue2;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the characteristicvaluecoded property.
     * 
     * @return
     *     possible object is
     *     {@link CHARACTERISTICVALUECODED }
     *     
     */
    public CHARACTERISTICVALUECODED getCHARACTERISTICVALUECODED() {
        return characteristicvaluecoded;
    }

    /**
     * Sets the value of the characteristicvaluecoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHARACTERISTICVALUECODED }
     *     
     */
    public void setCHARACTERISTICVALUECODED(CHARACTERISTICVALUECODED value) {
        this.characteristicvaluecoded = value;
    }

    /**
     * Gets the value of the codelistid property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTID }
     *     
     */
    public CODELISTID getCODELISTID() {
        return codelistid;
    }

    /**
     * Sets the value of the codelistid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTID }
     *     
     */
    public void setCODELISTID(CODELISTID value) {
        this.codelistid = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link AGENCY }
     *     
     */
    public AGENCY getAGENCY() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGENCY }
     *     
     */
    public void setAGENCY(AGENCY value) {
        this.agency = value;
    }

    /**
     * Gets the value of the characteristicvalue1 property.
     * 
     * @return
     *     possible object is
     *     {@link CHARACTERISTICVALUE1 }
     *     
     */
    public CHARACTERISTICVALUE1 getCHARACTERISTICVALUE1() {
        return characteristicvalue1;
    }

    /**
     * Sets the value of the characteristicvalue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHARACTERISTICVALUE1 }
     *     
     */
    public void setCHARACTERISTICVALUE1(CHARACTERISTICVALUE1 value) {
        this.characteristicvalue1 = value;
    }

    /**
     * Gets the value of the characteristicvalue2 property.
     * 
     * @return
     *     possible object is
     *     {@link CHARACTERISTICVALUE2 }
     *     
     */
    public CHARACTERISTICVALUE2 getCHARACTERISTICVALUE2() {
        return characteristicvalue2;
    }

    /**
     * Sets the value of the characteristicvalue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHARACTERISTICVALUE2 }
     *     
     */
    public void setCHARACTERISTICVALUE2(CHARACTERISTICVALUE2 value) {
        this.characteristicvalue2 = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
