//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ACTION" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNER" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODELIST" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODELISTAGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}NAMEADDRESS1" minOccurs="0"/&gt;
 *         &lt;element ref="{}NAMEADDRESS2" minOccurs="0"/&gt;
 *         &lt;element ref="{}NAMEADDRESS3" minOccurs="0"/&gt;
 *         &lt;element ref="{}NAMEADDRESS4" minOccurs="0"/&gt;
 *         &lt;element ref="{}NAMEADDRESS5" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNERNAME1" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNERNAME2" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNERNAME3" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNERNAME4" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNERNAME5" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTNERFORMAT" minOccurs="0"/&gt;
 *         &lt;element ref="{}STREET1" minOccurs="0"/&gt;
 *         &lt;element ref="{}STREET2" minOccurs="0"/&gt;
 *         &lt;element ref="{}STREET3" minOccurs="0"/&gt;
 *         &lt;element ref="{}STREET4" minOccurs="0"/&gt;
 *         &lt;element ref="{}CITY" minOccurs="0"/&gt;
 *         &lt;element ref="{}REGION" minOccurs="0"/&gt;
 *         &lt;element ref="{}ZIPCODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}COUNTRY" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWRFF_4" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWFII_4" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWCTA_2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "action",
    "partner",
    "codelist",
    "codelistagency",
    "nameaddress1",
    "nameaddress2",
    "nameaddress3",
    "nameaddress4",
    "nameaddress5",
    "partnername1",
    "partnername2",
    "partnername3",
    "partnername4",
    "partnername5",
    "partnerformat",
    "street1",
    "street2",
    "street3",
    "street4",
    "city",
    "region",
    "zipcode",
    "country",
    "e1VDEWRFF4",
    "e1VDEWFII4",
    "e1VDEWCTA2"
})
@XmlRootElement(name = "E1VDEWNAD_4")
public class E1VDEWNAD4 {

    @XmlElement(name = "ACTION")
    protected ACTION action;
    @XmlElement(name = "PARTNER")
    protected PARTNER partner;
    @XmlElement(name = "CODELIST")
    protected CODELIST codelist;
    @XmlElement(name = "CODELISTAGENCY")
    protected CODELISTAGENCY codelistagency;
    @XmlElement(name = "NAMEADDRESS1")
    protected NAMEADDRESS1 nameaddress1;
    @XmlElement(name = "NAMEADDRESS2")
    protected NAMEADDRESS2 nameaddress2;
    @XmlElement(name = "NAMEADDRESS3")
    protected NAMEADDRESS3 nameaddress3;
    @XmlElement(name = "NAMEADDRESS4")
    protected NAMEADDRESS4 nameaddress4;
    @XmlElement(name = "NAMEADDRESS5")
    protected NAMEADDRESS5 nameaddress5;
    @XmlElement(name = "PARTNERNAME1")
    protected PARTNERNAME1 partnername1;
    @XmlElement(name = "PARTNERNAME2")
    protected PARTNERNAME2 partnername2;
    @XmlElement(name = "PARTNERNAME3")
    protected PARTNERNAME3 partnername3;
    @XmlElement(name = "PARTNERNAME4")
    protected PARTNERNAME4 partnername4;
    @XmlElement(name = "PARTNERNAME5")
    protected PARTNERNAME5 partnername5;
    @XmlElement(name = "PARTNERFORMAT")
    protected PARTNERFORMAT partnerformat;
    @XmlElement(name = "STREET1")
    protected STREET1 street1;
    @XmlElement(name = "STREET2")
    protected STREET2 street2;
    @XmlElement(name = "STREET3")
    protected STREET3 street3;
    @XmlElement(name = "STREET4")
    protected STREET4 street4;
    @XmlElement(name = "CITY")
    protected CITY city;
    @XmlElement(name = "REGION")
    protected REGION region;
    @XmlElement(name = "ZIPCODE")
    protected ZIPCODE zipcode;
    @XmlElement(name = "COUNTRY")
    protected COUNTRY country;
    @XmlElement(name = "E1VDEWRFF_4")
    protected List<E1VDEWRFF4> e1VDEWRFF4;
    @XmlElement(name = "E1VDEWFII_4")
    protected E1VDEWFII4 e1VDEWFII4;
    @XmlElement(name = "E1VDEWCTA_2")
    protected List<E1VDEWCTA2> e1VDEWCTA2;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ACTION }
     *     
     */
    public ACTION getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACTION }
     *     
     */
    public void setACTION(ACTION value) {
        this.action = value;
    }

    /**
     * Gets the value of the partner property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNER }
     *     
     */
    public PARTNER getPARTNER() {
        return partner;
    }

    /**
     * Sets the value of the partner property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNER }
     *     
     */
    public void setPARTNER(PARTNER value) {
        this.partner = value;
    }

    /**
     * Gets the value of the codelist property.
     * 
     * @return
     *     possible object is
     *     {@link CODELIST }
     *     
     */
    public CODELIST getCODELIST() {
        return codelist;
    }

    /**
     * Sets the value of the codelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELIST }
     *     
     */
    public void setCODELIST(CODELIST value) {
        this.codelist = value;
    }

    /**
     * Gets the value of the codelistagency property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTAGENCY }
     *     
     */
    public CODELISTAGENCY getCODELISTAGENCY() {
        return codelistagency;
    }

    /**
     * Sets the value of the codelistagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTAGENCY }
     *     
     */
    public void setCODELISTAGENCY(CODELISTAGENCY value) {
        this.codelistagency = value;
    }

    /**
     * Gets the value of the nameaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link NAMEADDRESS1 }
     *     
     */
    public NAMEADDRESS1 getNAMEADDRESS1() {
        return nameaddress1;
    }

    /**
     * Sets the value of the nameaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAMEADDRESS1 }
     *     
     */
    public void setNAMEADDRESS1(NAMEADDRESS1 value) {
        this.nameaddress1 = value;
    }

    /**
     * Gets the value of the nameaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link NAMEADDRESS2 }
     *     
     */
    public NAMEADDRESS2 getNAMEADDRESS2() {
        return nameaddress2;
    }

    /**
     * Sets the value of the nameaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAMEADDRESS2 }
     *     
     */
    public void setNAMEADDRESS2(NAMEADDRESS2 value) {
        this.nameaddress2 = value;
    }

    /**
     * Gets the value of the nameaddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link NAMEADDRESS3 }
     *     
     */
    public NAMEADDRESS3 getNAMEADDRESS3() {
        return nameaddress3;
    }

    /**
     * Sets the value of the nameaddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAMEADDRESS3 }
     *     
     */
    public void setNAMEADDRESS3(NAMEADDRESS3 value) {
        this.nameaddress3 = value;
    }

    /**
     * Gets the value of the nameaddress4 property.
     * 
     * @return
     *     possible object is
     *     {@link NAMEADDRESS4 }
     *     
     */
    public NAMEADDRESS4 getNAMEADDRESS4() {
        return nameaddress4;
    }

    /**
     * Sets the value of the nameaddress4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAMEADDRESS4 }
     *     
     */
    public void setNAMEADDRESS4(NAMEADDRESS4 value) {
        this.nameaddress4 = value;
    }

    /**
     * Gets the value of the nameaddress5 property.
     * 
     * @return
     *     possible object is
     *     {@link NAMEADDRESS5 }
     *     
     */
    public NAMEADDRESS5 getNAMEADDRESS5() {
        return nameaddress5;
    }

    /**
     * Sets the value of the nameaddress5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAMEADDRESS5 }
     *     
     */
    public void setNAMEADDRESS5(NAMEADDRESS5 value) {
        this.nameaddress5 = value;
    }

    /**
     * Gets the value of the partnername1 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNERNAME1 }
     *     
     */
    public PARTNERNAME1 getPARTNERNAME1() {
        return partnername1;
    }

    /**
     * Sets the value of the partnername1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNERNAME1 }
     *     
     */
    public void setPARTNERNAME1(PARTNERNAME1 value) {
        this.partnername1 = value;
    }

    /**
     * Gets the value of the partnername2 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNERNAME2 }
     *     
     */
    public PARTNERNAME2 getPARTNERNAME2() {
        return partnername2;
    }

    /**
     * Sets the value of the partnername2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNERNAME2 }
     *     
     */
    public void setPARTNERNAME2(PARTNERNAME2 value) {
        this.partnername2 = value;
    }

    /**
     * Gets the value of the partnername3 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNERNAME3 }
     *     
     */
    public PARTNERNAME3 getPARTNERNAME3() {
        return partnername3;
    }

    /**
     * Sets the value of the partnername3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNERNAME3 }
     *     
     */
    public void setPARTNERNAME3(PARTNERNAME3 value) {
        this.partnername3 = value;
    }

    /**
     * Gets the value of the partnername4 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNERNAME4 }
     *     
     */
    public PARTNERNAME4 getPARTNERNAME4() {
        return partnername4;
    }

    /**
     * Sets the value of the partnername4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNERNAME4 }
     *     
     */
    public void setPARTNERNAME4(PARTNERNAME4 value) {
        this.partnername4 = value;
    }

    /**
     * Gets the value of the partnername5 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNERNAME5 }
     *     
     */
    public PARTNERNAME5 getPARTNERNAME5() {
        return partnername5;
    }

    /**
     * Sets the value of the partnername5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNERNAME5 }
     *     
     */
    public void setPARTNERNAME5(PARTNERNAME5 value) {
        this.partnername5 = value;
    }

    /**
     * Gets the value of the partnerformat property.
     * 
     * @return
     *     possible object is
     *     {@link PARTNERFORMAT }
     *     
     */
    public PARTNERFORMAT getPARTNERFORMAT() {
        return partnerformat;
    }

    /**
     * Sets the value of the partnerformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTNERFORMAT }
     *     
     */
    public void setPARTNERFORMAT(PARTNERFORMAT value) {
        this.partnerformat = value;
    }

    /**
     * Gets the value of the street1 property.
     * 
     * @return
     *     possible object is
     *     {@link STREET1 }
     *     
     */
    public STREET1 getSTREET1() {
        return street1;
    }

    /**
     * Sets the value of the street1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link STREET1 }
     *     
     */
    public void setSTREET1(STREET1 value) {
        this.street1 = value;
    }

    /**
     * Gets the value of the street2 property.
     * 
     * @return
     *     possible object is
     *     {@link STREET2 }
     *     
     */
    public STREET2 getSTREET2() {
        return street2;
    }

    /**
     * Sets the value of the street2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link STREET2 }
     *     
     */
    public void setSTREET2(STREET2 value) {
        this.street2 = value;
    }

    /**
     * Gets the value of the street3 property.
     * 
     * @return
     *     possible object is
     *     {@link STREET3 }
     *     
     */
    public STREET3 getSTREET3() {
        return street3;
    }

    /**
     * Sets the value of the street3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link STREET3 }
     *     
     */
    public void setSTREET3(STREET3 value) {
        this.street3 = value;
    }

    /**
     * Gets the value of the street4 property.
     * 
     * @return
     *     possible object is
     *     {@link STREET4 }
     *     
     */
    public STREET4 getSTREET4() {
        return street4;
    }

    /**
     * Sets the value of the street4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link STREET4 }
     *     
     */
    public void setSTREET4(STREET4 value) {
        this.street4 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link CITY }
     *     
     */
    public CITY getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link CITY }
     *     
     */
    public void setCITY(CITY value) {
        this.city = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link REGION }
     *     
     */
    public REGION getREGION() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link REGION }
     *     
     */
    public void setREGION(REGION value) {
        this.region = value;
    }

    /**
     * Gets the value of the zipcode property.
     * 
     * @return
     *     possible object is
     *     {@link ZIPCODE }
     *     
     */
    public ZIPCODE getZIPCODE() {
        return zipcode;
    }

    /**
     * Sets the value of the zipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZIPCODE }
     *     
     */
    public void setZIPCODE(ZIPCODE value) {
        this.zipcode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link COUNTRY }
     *     
     */
    public COUNTRY getCOUNTRY() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link COUNTRY }
     *     
     */
    public void setCOUNTRY(COUNTRY value) {
        this.country = value;
    }

    /**
     * Gets the value of the e1VDEWRFF4 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWRFF4 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWRFF4().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWRFF4 }
     * 
     * 
     */
    public List<E1VDEWRFF4> getE1VDEWRFF4() {
        if (e1VDEWRFF4 == null) {
            e1VDEWRFF4 = new ArrayList<E1VDEWRFF4>();
        }
        return this.e1VDEWRFF4;
    }

    /**
     * Gets the value of the e1VDEWFII4 property.
     * 
     * @return
     *     possible object is
     *     {@link E1VDEWFII4 }
     *     
     */
    public E1VDEWFII4 getE1VDEWFII4() {
        return e1VDEWFII4;
    }

    /**
     * Sets the value of the e1VDEWFII4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link E1VDEWFII4 }
     *     
     */
    public void setE1VDEWFII4(E1VDEWFII4 value) {
        this.e1VDEWFII4 = value;
    }

    /**
     * Gets the value of the e1VDEWCTA2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWCTA2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWCTA2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWCTA2 }
     * 
     * 
     */
    public List<E1VDEWCTA2> getE1VDEWCTA2() {
        if (e1VDEWCTA2 == null) {
            e1VDEWCTA2 = new ArrayList<E1VDEWCTA2>();
        }
        return this.e1VDEWCTA2;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
