//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}OBJECT_TYPE" minOccurs="0"/&gt;
 *         &lt;element ref="{}ID_NUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}ID_CODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}ID_STATUS" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTY_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTY_ID_CODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTY_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}STATUS_DESCR" minOccurs="0"/&gt;
 *         &lt;element ref="{}CONF_LEVEL" minOccurs="0"/&gt;
 *         &lt;element ref="{}POS_HIERARCHI" minOccurs="0"/&gt;
 *         &lt;element ref="{}POS_SEQUENCE_NR" minOccurs="0"/&gt;
 *         &lt;element ref="{}PRODUCT_DESCR" minOccurs="0"/&gt;
 *         &lt;element ref="{}PRODUCT_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}PRODUCT_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}PRODUCT_CHARACTERISTIC_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}PRODUCT_CHARACTERISTIC_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWLOC_3" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}E1VDEWDTM_3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWSTS_2" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}E1VDEWTAX_3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWFTX_2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWAGR" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWINP" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWRFF_2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWCCI_3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWSEQ_2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWMOA_6" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWNAD_4" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttype",
    "idnumber",
    "idcode",
    "idstatus",
    "partyid",
    "partyidcode",
    "partyagency",
    "statusdescr",
    "conflevel",
    "poshierarchi",
    "possequencenr",
    "productdescr",
    "productid",
    "productagency",
    "productcharacteristic1",
    "productcharacteristic2",
    "e1VDEWLOC3",
    "e1VDEWDTM3",
    "e1VDEWSTS2",
    "e1VDEWTAX3",
    "e1VDEWFTX2",
    "e1VDEWAGR",
    "e1VDEWINP",
    "e1VDEWRFF2",
    "e1VDEWCCI3",
    "e1VDEWSEQ2",
    "e1VDEWMOA6",
    "e1VDEWNAD4"
})
@XmlRootElement(name = "E1VDEWIDE_2")
public class E1VDEWIDE2 {

    @XmlElement(name = "OBJECT_TYPE")
    protected OBJECTTYPE objecttype;
    @XmlElement(name = "ID_NUMBER")
    protected IDNUMBER idnumber;
    @XmlElement(name = "ID_CODE")
    protected IDCODE idcode;
    @XmlElement(name = "ID_STATUS")
    protected IDSTATUS idstatus;
    @XmlElement(name = "PARTY_ID")
    protected PARTYID partyid;
    @XmlElement(name = "PARTY_ID_CODE")
    protected PARTYIDCODE partyidcode;
    @XmlElement(name = "PARTY_AGENCY")
    protected PARTYAGENCY partyagency;
    @XmlElement(name = "STATUS_DESCR")
    protected STATUSDESCR statusdescr;
    @XmlElement(name = "CONF_LEVEL")
    protected CONFLEVEL conflevel;
    @XmlElement(name = "POS_HIERARCHI")
    protected POSHIERARCHI poshierarchi;
    @XmlElement(name = "POS_SEQUENCE_NR")
    protected POSSEQUENCENR possequencenr;
    @XmlElement(name = "PRODUCT_DESCR")
    protected PRODUCTDESCR productdescr;
    @XmlElement(name = "PRODUCT_ID")
    protected PRODUCTID productid;
    @XmlElement(name = "PRODUCT_AGENCY")
    protected PRODUCTAGENCY productagency;
    @XmlElement(name = "PRODUCT_CHARACTERISTIC_1")
    protected PRODUCTCHARACTERISTIC1 productcharacteristic1;
    @XmlElement(name = "PRODUCT_CHARACTERISTIC_2")
    protected PRODUCTCHARACTERISTIC2 productcharacteristic2;
    @XmlElement(name = "E1VDEWLOC_3", required = true)
    protected List<E1VDEWLOC3> e1VDEWLOC3;
    @XmlElement(name = "E1VDEWDTM_3")
    protected List<E1VDEWDTM3> e1VDEWDTM3;
    @XmlElement(name = "E1VDEWSTS_2", required = true)
    protected List<E1VDEWSTS2> e1VDEWSTS2;
    @XmlElement(name = "E1VDEWTAX_3")
    protected List<E1VDEWTAX3> e1VDEWTAX3;
    @XmlElement(name = "E1VDEWFTX_2")
    protected List<E1VDEWFTX2> e1VDEWFTX2;
    @XmlElement(name = "E1VDEWAGR")
    protected List<E1VDEWAGR> e1VDEWAGR;
    @XmlElement(name = "E1VDEWINP")
    protected List<E1VDEWINP> e1VDEWINP;
    @XmlElement(name = "E1VDEWRFF_2")
    protected List<E1VDEWRFF2> e1VDEWRFF2;
    @XmlElement(name = "E1VDEWCCI_3")
    protected List<E1VDEWCCI3> e1VDEWCCI3;
    @XmlElement(name = "E1VDEWSEQ_2")
    protected List<E1VDEWSEQ2> e1VDEWSEQ2;
    @XmlElement(name = "E1VDEWMOA_6")
    protected List<E1VDEWMOA6> e1VDEWMOA6;
    @XmlElement(name = "E1VDEWNAD_4")
    protected List<E1VDEWNAD4> e1VDEWNAD4;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the objecttype property.
     * 
     * @return
     *     possible object is
     *     {@link OBJECTTYPE }
     *     
     */
    public OBJECTTYPE getOBJECTTYPE() {
        return objecttype;
    }

    /**
     * Sets the value of the objecttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link OBJECTTYPE }
     *     
     */
    public void setOBJECTTYPE(OBJECTTYPE value) {
        this.objecttype = value;
    }

    /**
     * Gets the value of the idnumber property.
     * 
     * @return
     *     possible object is
     *     {@link IDNUMBER }
     *     
     */
    public IDNUMBER getIDNUMBER() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDNUMBER }
     *     
     */
    public void setIDNUMBER(IDNUMBER value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the idcode property.
     * 
     * @return
     *     possible object is
     *     {@link IDCODE }
     *     
     */
    public IDCODE getIDCODE() {
        return idcode;
    }

    /**
     * Sets the value of the idcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDCODE }
     *     
     */
    public void setIDCODE(IDCODE value) {
        this.idcode = value;
    }

    /**
     * Gets the value of the idstatus property.
     * 
     * @return
     *     possible object is
     *     {@link IDSTATUS }
     *     
     */
    public IDSTATUS getIDSTATUS() {
        return idstatus;
    }

    /**
     * Sets the value of the idstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDSTATUS }
     *     
     */
    public void setIDSTATUS(IDSTATUS value) {
        this.idstatus = value;
    }

    /**
     * Gets the value of the partyid property.
     * 
     * @return
     *     possible object is
     *     {@link PARTYID }
     *     
     */
    public PARTYID getPARTYID() {
        return partyid;
    }

    /**
     * Sets the value of the partyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTYID }
     *     
     */
    public void setPARTYID(PARTYID value) {
        this.partyid = value;
    }

    /**
     * Gets the value of the partyidcode property.
     * 
     * @return
     *     possible object is
     *     {@link PARTYIDCODE }
     *     
     */
    public PARTYIDCODE getPARTYIDCODE() {
        return partyidcode;
    }

    /**
     * Sets the value of the partyidcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTYIDCODE }
     *     
     */
    public void setPARTYIDCODE(PARTYIDCODE value) {
        this.partyidcode = value;
    }

    /**
     * Gets the value of the partyagency property.
     * 
     * @return
     *     possible object is
     *     {@link PARTYAGENCY }
     *     
     */
    public PARTYAGENCY getPARTYAGENCY() {
        return partyagency;
    }

    /**
     * Sets the value of the partyagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTYAGENCY }
     *     
     */
    public void setPARTYAGENCY(PARTYAGENCY value) {
        this.partyagency = value;
    }

    /**
     * Gets the value of the statusdescr property.
     * 
     * @return
     *     possible object is
     *     {@link STATUSDESCR }
     *     
     */
    public STATUSDESCR getSTATUSDESCR() {
        return statusdescr;
    }

    /**
     * Sets the value of the statusdescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link STATUSDESCR }
     *     
     */
    public void setSTATUSDESCR(STATUSDESCR value) {
        this.statusdescr = value;
    }

    /**
     * Gets the value of the conflevel property.
     * 
     * @return
     *     possible object is
     *     {@link CONFLEVEL }
     *     
     */
    public CONFLEVEL getCONFLEVEL() {
        return conflevel;
    }

    /**
     * Sets the value of the conflevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFLEVEL }
     *     
     */
    public void setCONFLEVEL(CONFLEVEL value) {
        this.conflevel = value;
    }

    /**
     * Gets the value of the poshierarchi property.
     * 
     * @return
     *     possible object is
     *     {@link POSHIERARCHI }
     *     
     */
    public POSHIERARCHI getPOSHIERARCHI() {
        return poshierarchi;
    }

    /**
     * Sets the value of the poshierarchi property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSHIERARCHI }
     *     
     */
    public void setPOSHIERARCHI(POSHIERARCHI value) {
        this.poshierarchi = value;
    }

    /**
     * Gets the value of the possequencenr property.
     * 
     * @return
     *     possible object is
     *     {@link POSSEQUENCENR }
     *     
     */
    public POSSEQUENCENR getPOSSEQUENCENR() {
        return possequencenr;
    }

    /**
     * Sets the value of the possequencenr property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSSEQUENCENR }
     *     
     */
    public void setPOSSEQUENCENR(POSSEQUENCENR value) {
        this.possequencenr = value;
    }

    /**
     * Gets the value of the productdescr property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTDESCR }
     *     
     */
    public PRODUCTDESCR getPRODUCTDESCR() {
        return productdescr;
    }

    /**
     * Sets the value of the productdescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTDESCR }
     *     
     */
    public void setPRODUCTDESCR(PRODUCTDESCR value) {
        this.productdescr = value;
    }

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTID }
     *     
     */
    public PRODUCTID getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTID }
     *     
     */
    public void setPRODUCTID(PRODUCTID value) {
        this.productid = value;
    }

    /**
     * Gets the value of the productagency property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTAGENCY }
     *     
     */
    public PRODUCTAGENCY getPRODUCTAGENCY() {
        return productagency;
    }

    /**
     * Sets the value of the productagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTAGENCY }
     *     
     */
    public void setPRODUCTAGENCY(PRODUCTAGENCY value) {
        this.productagency = value;
    }

    /**
     * Gets the value of the productcharacteristic1 property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTCHARACTERISTIC1 }
     *     
     */
    public PRODUCTCHARACTERISTIC1 getPRODUCTCHARACTERISTIC1() {
        return productcharacteristic1;
    }

    /**
     * Sets the value of the productcharacteristic1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTCHARACTERISTIC1 }
     *     
     */
    public void setPRODUCTCHARACTERISTIC1(PRODUCTCHARACTERISTIC1 value) {
        this.productcharacteristic1 = value;
    }

    /**
     * Gets the value of the productcharacteristic2 property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTCHARACTERISTIC2 }
     *     
     */
    public PRODUCTCHARACTERISTIC2 getPRODUCTCHARACTERISTIC2() {
        return productcharacteristic2;
    }

    /**
     * Sets the value of the productcharacteristic2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTCHARACTERISTIC2 }
     *     
     */
    public void setPRODUCTCHARACTERISTIC2(PRODUCTCHARACTERISTIC2 value) {
        this.productcharacteristic2 = value;
    }

    /**
     * Gets the value of the e1VDEWLOC3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWLOC3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWLOC3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWLOC3 }
     * 
     * 
     */
    public List<E1VDEWLOC3> getE1VDEWLOC3() {
        if (e1VDEWLOC3 == null) {
            e1VDEWLOC3 = new ArrayList<E1VDEWLOC3>();
        }
        return this.e1VDEWLOC3;
    }

    /**
     * Gets the value of the e1VDEWDTM3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWDTM3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWDTM3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWDTM3 }
     * 
     * 
     */
    public List<E1VDEWDTM3> getE1VDEWDTM3() {
        if (e1VDEWDTM3 == null) {
            e1VDEWDTM3 = new ArrayList<E1VDEWDTM3>();
        }
        return this.e1VDEWDTM3;
    }

    /**
     * Gets the value of the e1VDEWSTS2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWSTS2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWSTS2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWSTS2 }
     * 
     * 
     */
    public List<E1VDEWSTS2> getE1VDEWSTS2() {
        if (e1VDEWSTS2 == null) {
            e1VDEWSTS2 = new ArrayList<E1VDEWSTS2>();
        }
        return this.e1VDEWSTS2;
    }

    /**
     * Gets the value of the e1VDEWTAX3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWTAX3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWTAX3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWTAX3 }
     * 
     * 
     */
    public List<E1VDEWTAX3> getE1VDEWTAX3() {
        if (e1VDEWTAX3 == null) {
            e1VDEWTAX3 = new ArrayList<E1VDEWTAX3>();
        }
        return this.e1VDEWTAX3;
    }

    /**
     * Gets the value of the e1VDEWFTX2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWFTX2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWFTX2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWFTX2 }
     * 
     * 
     */
    public List<E1VDEWFTX2> getE1VDEWFTX2() {
        if (e1VDEWFTX2 == null) {
            e1VDEWFTX2 = new ArrayList<E1VDEWFTX2>();
        }
        return this.e1VDEWFTX2;
    }

    /**
     * Gets the value of the e1VDEWAGR property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWAGR property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWAGR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWAGR }
     * 
     * 
     */
    public List<E1VDEWAGR> getE1VDEWAGR() {
        if (e1VDEWAGR == null) {
            e1VDEWAGR = new ArrayList<E1VDEWAGR>();
        }
        return this.e1VDEWAGR;
    }

    /**
     * Gets the value of the e1VDEWINP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWINP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWINP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWINP }
     * 
     * 
     */
    public List<E1VDEWINP> getE1VDEWINP() {
        if (e1VDEWINP == null) {
            e1VDEWINP = new ArrayList<E1VDEWINP>();
        }
        return this.e1VDEWINP;
    }

    /**
     * Gets the value of the e1VDEWRFF2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWRFF2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWRFF2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWRFF2 }
     * 
     * 
     */
    public List<E1VDEWRFF2> getE1VDEWRFF2() {
        if (e1VDEWRFF2 == null) {
            e1VDEWRFF2 = new ArrayList<E1VDEWRFF2>();
        }
        return this.e1VDEWRFF2;
    }

    /**
     * Gets the value of the e1VDEWCCI3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWCCI3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWCCI3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWCCI3 }
     * 
     * 
     */
    public List<E1VDEWCCI3> getE1VDEWCCI3() {
        if (e1VDEWCCI3 == null) {
            e1VDEWCCI3 = new ArrayList<E1VDEWCCI3>();
        }
        return this.e1VDEWCCI3;
    }

    /**
     * Gets the value of the e1VDEWSEQ2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWSEQ2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWSEQ2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWSEQ2 }
     * 
     * 
     */
    public List<E1VDEWSEQ2> getE1VDEWSEQ2() {
        if (e1VDEWSEQ2 == null) {
            e1VDEWSEQ2 = new ArrayList<E1VDEWSEQ2>();
        }
        return this.e1VDEWSEQ2;
    }

    /**
     * Gets the value of the e1VDEWMOA6 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWMOA6 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWMOA6().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWMOA6 }
     * 
     * 
     */
    public List<E1VDEWMOA6> getE1VDEWMOA6() {
        if (e1VDEWMOA6 == null) {
            e1VDEWMOA6 = new ArrayList<E1VDEWMOA6>();
        }
        return this.e1VDEWMOA6;
    }

    /**
     * Gets the value of the e1VDEWNAD4 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWNAD4 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWNAD4().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWNAD4 }
     * 
     * 
     */
    public List<E1VDEWNAD4> getE1VDEWNAD4() {
        if (e1VDEWNAD4 == null) {
            e1VDEWNAD4 = new ArrayList<E1VDEWNAD4>();
        }
        return this.e1VDEWNAD4;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
