//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ACTION_REQUEST" minOccurs="0"/&gt;
 *         &lt;element ref="{}SEQU_INFOS_SEQUENCENR" minOccurs="0"/&gt;
 *         &lt;element ref="{}SEQU_INFOS_SEQUENCENR_CODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}SEQU_INFOS_CODE_LIST" minOccurs="0"/&gt;
 *         &lt;element ref="{}SEQU_INFOS_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWPIA_2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWQTY" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWCCI_4" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actionrequest",
    "sequinfossequencenr",
    "sequinfossequencenrcode",
    "sequinfoscodelist",
    "sequinfosagency",
    "e1VDEWPIA2",
    "e1VDEWQTY",
    "e1VDEWCCI4"
})
@XmlRootElement(name = "E1VDEWSEQ_2")
public class E1VDEWSEQ2 {

    @XmlElement(name = "ACTION_REQUEST")
    protected ACTIONREQUEST actionrequest;
    @XmlElement(name = "SEQU_INFOS_SEQUENCENR")
    protected SEQUINFOSSEQUENCENR sequinfossequencenr;
    @XmlElement(name = "SEQU_INFOS_SEQUENCENR_CODE")
    protected SEQUINFOSSEQUENCENRCODE sequinfossequencenrcode;
    @XmlElement(name = "SEQU_INFOS_CODE_LIST")
    protected SEQUINFOSCODELIST sequinfoscodelist;
    @XmlElement(name = "SEQU_INFOS_AGENCY")
    protected SEQUINFOSAGENCY sequinfosagency;
    @XmlElement(name = "E1VDEWPIA_2")
    protected List<E1VDEWPIA2> e1VDEWPIA2;
    @XmlElement(name = "E1VDEWQTY")
    protected List<E1VDEWQTY> e1VDEWQTY;
    @XmlElement(name = "E1VDEWCCI_4")
    protected List<E1VDEWCCI4> e1VDEWCCI4;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the actionrequest property.
     * 
     * @return
     *     possible object is
     *     {@link ACTIONREQUEST }
     *     
     */
    public ACTIONREQUEST getACTIONREQUEST() {
        return actionrequest;
    }

    /**
     * Sets the value of the actionrequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACTIONREQUEST }
     *     
     */
    public void setACTIONREQUEST(ACTIONREQUEST value) {
        this.actionrequest = value;
    }

    /**
     * Gets the value of the sequinfossequencenr property.
     * 
     * @return
     *     possible object is
     *     {@link SEQUINFOSSEQUENCENR }
     *     
     */
    public SEQUINFOSSEQUENCENR getSEQUINFOSSEQUENCENR() {
        return sequinfossequencenr;
    }

    /**
     * Sets the value of the sequinfossequencenr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQUINFOSSEQUENCENR }
     *     
     */
    public void setSEQUINFOSSEQUENCENR(SEQUINFOSSEQUENCENR value) {
        this.sequinfossequencenr = value;
    }

    /**
     * Gets the value of the sequinfossequencenrcode property.
     * 
     * @return
     *     possible object is
     *     {@link SEQUINFOSSEQUENCENRCODE }
     *     
     */
    public SEQUINFOSSEQUENCENRCODE getSEQUINFOSSEQUENCENRCODE() {
        return sequinfossequencenrcode;
    }

    /**
     * Sets the value of the sequinfossequencenrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQUINFOSSEQUENCENRCODE }
     *     
     */
    public void setSEQUINFOSSEQUENCENRCODE(SEQUINFOSSEQUENCENRCODE value) {
        this.sequinfossequencenrcode = value;
    }

    /**
     * Gets the value of the sequinfoscodelist property.
     * 
     * @return
     *     possible object is
     *     {@link SEQUINFOSCODELIST }
     *     
     */
    public SEQUINFOSCODELIST getSEQUINFOSCODELIST() {
        return sequinfoscodelist;
    }

    /**
     * Sets the value of the sequinfoscodelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQUINFOSCODELIST }
     *     
     */
    public void setSEQUINFOSCODELIST(SEQUINFOSCODELIST value) {
        this.sequinfoscodelist = value;
    }

    /**
     * Gets the value of the sequinfosagency property.
     * 
     * @return
     *     possible object is
     *     {@link SEQUINFOSAGENCY }
     *     
     */
    public SEQUINFOSAGENCY getSEQUINFOSAGENCY() {
        return sequinfosagency;
    }

    /**
     * Sets the value of the sequinfosagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQUINFOSAGENCY }
     *     
     */
    public void setSEQUINFOSAGENCY(SEQUINFOSAGENCY value) {
        this.sequinfosagency = value;
    }

    /**
     * Gets the value of the e1VDEWPIA2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWPIA2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWPIA2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWPIA2 }
     * 
     * 
     */
    public List<E1VDEWPIA2> getE1VDEWPIA2() {
        if (e1VDEWPIA2 == null) {
            e1VDEWPIA2 = new ArrayList<E1VDEWPIA2>();
        }
        return this.e1VDEWPIA2;
    }

    /**
     * Gets the value of the e1VDEWQTY property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWQTY property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWQTY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWQTY }
     * 
     * 
     */
    public List<E1VDEWQTY> getE1VDEWQTY() {
        if (e1VDEWQTY == null) {
            e1VDEWQTY = new ArrayList<E1VDEWQTY>();
        }
        return this.e1VDEWQTY;
    }

    /**
     * Gets the value of the e1VDEWCCI4 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWCCI4 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWCCI4().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWCCI4 }
     * 
     * 
     */
    public List<E1VDEWCCI4> getE1VDEWCCI4() {
        if (e1VDEWCCI4 == null) {
            e1VDEWCCI4 = new ArrayList<E1VDEWCCI4>();
        }
        return this.e1VDEWCCI4;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
