//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PRODUCT_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_TYPE_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_TYPE_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_TYPE_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_4" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_TYPE_4" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_4" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_4" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_5" minOccurs="0"/&gt;
 *         &lt;element ref="{}ITEM_NUMBER_TYPE_5" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_5" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_5" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productid",
    "itemnumber1",
    "itemnumbertype1",
    "codelistqualifier1",
    "codelistresponsibleagency1",
    "itemnumber2",
    "itemnumbertype2",
    "codelistqualifier2",
    "codelistresponsibleagency2",
    "itemnumber3",
    "itemnumbertype3",
    "codelistqualifier3",
    "codelistresponsibleagency3",
    "itemnumber4",
    "itemnumbertype4",
    "codelistqualifier4",
    "codelistresponsibleagency4",
    "itemnumber5",
    "itemnumbertype5",
    "codelistqualifier5",
    "codelistresponsibleagency5"
})
@XmlRootElement(name = "E1VDEWPIA_2")
public class E1VDEWPIA2 {

    @XmlElement(name = "PRODUCT_ID")
    protected PRODUCTID productid;
    @XmlElement(name = "ITEM_NUMBER_1")
    protected ITEMNUMBER1 itemnumber1;
    @XmlElement(name = "ITEM_NUMBER_TYPE_1")
    protected ITEMNUMBERTYPE1 itemnumbertype1;
    @XmlElement(name = "CODE_LIST_QUALIFIER_1")
    protected CODELISTQUALIFIER1 codelistqualifier1;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_1")
    protected CODELISTRESPONSIBLEAGENCY1 codelistresponsibleagency1;
    @XmlElement(name = "ITEM_NUMBER_2")
    protected ITEMNUMBER2 itemnumber2;
    @XmlElement(name = "ITEM_NUMBER_TYPE_2")
    protected ITEMNUMBERTYPE2 itemnumbertype2;
    @XmlElement(name = "CODE_LIST_QUALIFIER_2")
    protected CODELISTQUALIFIER2 codelistqualifier2;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_2")
    protected CODELISTRESPONSIBLEAGENCY2 codelistresponsibleagency2;
    @XmlElement(name = "ITEM_NUMBER_3")
    protected ITEMNUMBER3 itemnumber3;
    @XmlElement(name = "ITEM_NUMBER_TYPE_3")
    protected ITEMNUMBERTYPE3 itemnumbertype3;
    @XmlElement(name = "CODE_LIST_QUALIFIER_3")
    protected CODELISTQUALIFIER3 codelistqualifier3;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_3")
    protected CODELISTRESPONSIBLEAGENCY3 codelistresponsibleagency3;
    @XmlElement(name = "ITEM_NUMBER_4")
    protected ITEMNUMBER4 itemnumber4;
    @XmlElement(name = "ITEM_NUMBER_TYPE_4")
    protected ITEMNUMBERTYPE4 itemnumbertype4;
    @XmlElement(name = "CODE_LIST_QUALIFIER_4")
    protected CODELISTQUALIFIER4 codelistqualifier4;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_4")
    protected CODELISTRESPONSIBLEAGENCY4 codelistresponsibleagency4;
    @XmlElement(name = "ITEM_NUMBER_5")
    protected ITEMNUMBER5 itemnumber5;
    @XmlElement(name = "ITEM_NUMBER_TYPE_5")
    protected ITEMNUMBERTYPE5 itemnumbertype5;
    @XmlElement(name = "CODE_LIST_QUALIFIER_5")
    protected CODELISTQUALIFIER5 codelistqualifier5;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_5")
    protected CODELISTRESPONSIBLEAGENCY5 codelistresponsibleagency5;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTID }
     *     
     */
    public PRODUCTID getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTID }
     *     
     */
    public void setPRODUCTID(PRODUCTID value) {
        this.productid = value;
    }

    /**
     * Gets the value of the itemnumber1 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBER1 }
     *     
     */
    public ITEMNUMBER1 getITEMNUMBER1() {
        return itemnumber1;
    }

    /**
     * Sets the value of the itemnumber1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBER1 }
     *     
     */
    public void setITEMNUMBER1(ITEMNUMBER1 value) {
        this.itemnumber1 = value;
    }

    /**
     * Gets the value of the itemnumbertype1 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBERTYPE1 }
     *     
     */
    public ITEMNUMBERTYPE1 getITEMNUMBERTYPE1() {
        return itemnumbertype1;
    }

    /**
     * Sets the value of the itemnumbertype1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBERTYPE1 }
     *     
     */
    public void setITEMNUMBERTYPE1(ITEMNUMBERTYPE1 value) {
        this.itemnumbertype1 = value;
    }

    /**
     * Gets the value of the codelistqualifier1 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER1 }
     *     
     */
    public CODELISTQUALIFIER1 getCODELISTQUALIFIER1() {
        return codelistqualifier1;
    }

    /**
     * Sets the value of the codelistqualifier1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER1 }
     *     
     */
    public void setCODELISTQUALIFIER1(CODELISTQUALIFIER1 value) {
        this.codelistqualifier1 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency1 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY1 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY1 getCODELISTRESPONSIBLEAGENCY1() {
        return codelistresponsibleagency1;
    }

    /**
     * Sets the value of the codelistresponsibleagency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY1 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY1(CODELISTRESPONSIBLEAGENCY1 value) {
        this.codelistresponsibleagency1 = value;
    }

    /**
     * Gets the value of the itemnumber2 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBER2 }
     *     
     */
    public ITEMNUMBER2 getITEMNUMBER2() {
        return itemnumber2;
    }

    /**
     * Sets the value of the itemnumber2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBER2 }
     *     
     */
    public void setITEMNUMBER2(ITEMNUMBER2 value) {
        this.itemnumber2 = value;
    }

    /**
     * Gets the value of the itemnumbertype2 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBERTYPE2 }
     *     
     */
    public ITEMNUMBERTYPE2 getITEMNUMBERTYPE2() {
        return itemnumbertype2;
    }

    /**
     * Sets the value of the itemnumbertype2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBERTYPE2 }
     *     
     */
    public void setITEMNUMBERTYPE2(ITEMNUMBERTYPE2 value) {
        this.itemnumbertype2 = value;
    }

    /**
     * Gets the value of the codelistqualifier2 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER2 }
     *     
     */
    public CODELISTQUALIFIER2 getCODELISTQUALIFIER2() {
        return codelistqualifier2;
    }

    /**
     * Sets the value of the codelistqualifier2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER2 }
     *     
     */
    public void setCODELISTQUALIFIER2(CODELISTQUALIFIER2 value) {
        this.codelistqualifier2 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency2 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY2 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY2 getCODELISTRESPONSIBLEAGENCY2() {
        return codelistresponsibleagency2;
    }

    /**
     * Sets the value of the codelistresponsibleagency2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY2 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY2(CODELISTRESPONSIBLEAGENCY2 value) {
        this.codelistresponsibleagency2 = value;
    }

    /**
     * Gets the value of the itemnumber3 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBER3 }
     *     
     */
    public ITEMNUMBER3 getITEMNUMBER3() {
        return itemnumber3;
    }

    /**
     * Sets the value of the itemnumber3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBER3 }
     *     
     */
    public void setITEMNUMBER3(ITEMNUMBER3 value) {
        this.itemnumber3 = value;
    }

    /**
     * Gets the value of the itemnumbertype3 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBERTYPE3 }
     *     
     */
    public ITEMNUMBERTYPE3 getITEMNUMBERTYPE3() {
        return itemnumbertype3;
    }

    /**
     * Sets the value of the itemnumbertype3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBERTYPE3 }
     *     
     */
    public void setITEMNUMBERTYPE3(ITEMNUMBERTYPE3 value) {
        this.itemnumbertype3 = value;
    }

    /**
     * Gets the value of the codelistqualifier3 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER3 }
     *     
     */
    public CODELISTQUALIFIER3 getCODELISTQUALIFIER3() {
        return codelistqualifier3;
    }

    /**
     * Sets the value of the codelistqualifier3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER3 }
     *     
     */
    public void setCODELISTQUALIFIER3(CODELISTQUALIFIER3 value) {
        this.codelistqualifier3 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency3 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY3 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY3 getCODELISTRESPONSIBLEAGENCY3() {
        return codelistresponsibleagency3;
    }

    /**
     * Sets the value of the codelistresponsibleagency3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY3 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY3(CODELISTRESPONSIBLEAGENCY3 value) {
        this.codelistresponsibleagency3 = value;
    }

    /**
     * Gets the value of the itemnumber4 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBER4 }
     *     
     */
    public ITEMNUMBER4 getITEMNUMBER4() {
        return itemnumber4;
    }

    /**
     * Sets the value of the itemnumber4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBER4 }
     *     
     */
    public void setITEMNUMBER4(ITEMNUMBER4 value) {
        this.itemnumber4 = value;
    }

    /**
     * Gets the value of the itemnumbertype4 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBERTYPE4 }
     *     
     */
    public ITEMNUMBERTYPE4 getITEMNUMBERTYPE4() {
        return itemnumbertype4;
    }

    /**
     * Sets the value of the itemnumbertype4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBERTYPE4 }
     *     
     */
    public void setITEMNUMBERTYPE4(ITEMNUMBERTYPE4 value) {
        this.itemnumbertype4 = value;
    }

    /**
     * Gets the value of the codelistqualifier4 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER4 }
     *     
     */
    public CODELISTQUALIFIER4 getCODELISTQUALIFIER4() {
        return codelistqualifier4;
    }

    /**
     * Sets the value of the codelistqualifier4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER4 }
     *     
     */
    public void setCODELISTQUALIFIER4(CODELISTQUALIFIER4 value) {
        this.codelistqualifier4 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency4 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY4 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY4 getCODELISTRESPONSIBLEAGENCY4() {
        return codelistresponsibleagency4;
    }

    /**
     * Sets the value of the codelistresponsibleagency4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY4 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY4(CODELISTRESPONSIBLEAGENCY4 value) {
        this.codelistresponsibleagency4 = value;
    }

    /**
     * Gets the value of the itemnumber5 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBER5 }
     *     
     */
    public ITEMNUMBER5 getITEMNUMBER5() {
        return itemnumber5;
    }

    /**
     * Sets the value of the itemnumber5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBER5 }
     *     
     */
    public void setITEMNUMBER5(ITEMNUMBER5 value) {
        this.itemnumber5 = value;
    }

    /**
     * Gets the value of the itemnumbertype5 property.
     * 
     * @return
     *     possible object is
     *     {@link ITEMNUMBERTYPE5 }
     *     
     */
    public ITEMNUMBERTYPE5 getITEMNUMBERTYPE5() {
        return itemnumbertype5;
    }

    /**
     * Sets the value of the itemnumbertype5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITEMNUMBERTYPE5 }
     *     
     */
    public void setITEMNUMBERTYPE5(ITEMNUMBERTYPE5 value) {
        this.itemnumbertype5 = value;
    }

    /**
     * Gets the value of the codelistqualifier5 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER5 }
     *     
     */
    public CODELISTQUALIFIER5 getCODELISTQUALIFIER5() {
        return codelistqualifier5;
    }

    /**
     * Sets the value of the codelistqualifier5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER5 }
     *     
     */
    public void setCODELISTQUALIFIER5(CODELISTQUALIFIER5 value) {
        this.codelistqualifier5 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency5 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY5 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY5 getCODELISTRESPONSIBLEAGENCY5() {
        return codelistresponsibleagency5;
    }

    /**
     * Sets the value of the codelistresponsibleagency5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY5 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY5(CODELISTRESPONSIBLEAGENCY5 value) {
        this.codelistresponsibleagency5 = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
