//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}REFERENCENUMBER"/&gt;
 *         &lt;element ref="{}IDENTIFIER"/&gt;
 *         &lt;element ref="{}VERSIONNUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}RELEASENUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}CONTROLAGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}ASSOCCODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCESSREF" minOccurs="0"/&gt;
 *         &lt;element ref="{}TRANSFERNUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}INDICATOR" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referencenumber",
    "identifier",
    "versionnumber",
    "releasenumber",
    "controlagency",
    "assoccode",
    "accessref",
    "transfernumber",
    "indicator"
})
@XmlRootElement(name = "E1VDEWUNH")
public class E1VDEWUNH {

    @XmlElement(name = "REFERENCENUMBER", required = true)
    protected REFERENCENUMBER referencenumber;
    @XmlElement(name = "IDENTIFIER", required = true)
    protected IDENTIFIER identifier;
    @XmlElement(name = "VERSIONNUMBER")
    protected VERSIONNUMBER versionnumber;
    @XmlElement(name = "RELEASENUMBER")
    protected RELEASENUMBER releasenumber;
    @XmlElement(name = "CONTROLAGENCY")
    protected CONTROLAGENCY controlagency;
    @XmlElement(name = "ASSOCCODE")
    protected ASSOCCODE assoccode;
    @XmlElement(name = "ACCESSREF")
    protected ACCESSREF accessref;
    @XmlElement(name = "TRANSFERNUMBER")
    protected TRANSFERNUMBER transfernumber;
    @XmlElement(name = "INDICATOR")
    protected INDICATOR indicator;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the referencenumber property.
     * 
     * @return
     *     possible object is
     *     {@link REFERENCENUMBER }
     *     
     */
    public REFERENCENUMBER getREFERENCENUMBER() {
        return referencenumber;
    }

    /**
     * Sets the value of the referencenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link REFERENCENUMBER }
     *     
     */
    public void setREFERENCENUMBER(REFERENCENUMBER value) {
        this.referencenumber = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IDENTIFIER }
     *     
     */
    public IDENTIFIER getIDENTIFIER() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDENTIFIER }
     *     
     */
    public void setIDENTIFIER(IDENTIFIER value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the versionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link VERSIONNUMBER }
     *     
     */
    public VERSIONNUMBER getVERSIONNUMBER() {
        return versionnumber;
    }

    /**
     * Sets the value of the versionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link VERSIONNUMBER }
     *     
     */
    public void setVERSIONNUMBER(VERSIONNUMBER value) {
        this.versionnumber = value;
    }

    /**
     * Gets the value of the releasenumber property.
     * 
     * @return
     *     possible object is
     *     {@link RELEASENUMBER }
     *     
     */
    public RELEASENUMBER getRELEASENUMBER() {
        return releasenumber;
    }

    /**
     * Sets the value of the releasenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELEASENUMBER }
     *     
     */
    public void setRELEASENUMBER(RELEASENUMBER value) {
        this.releasenumber = value;
    }

    /**
     * Gets the value of the controlagency property.
     * 
     * @return
     *     possible object is
     *     {@link CONTROLAGENCY }
     *     
     */
    public CONTROLAGENCY getCONTROLAGENCY() {
        return controlagency;
    }

    /**
     * Sets the value of the controlagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTROLAGENCY }
     *     
     */
    public void setCONTROLAGENCY(CONTROLAGENCY value) {
        this.controlagency = value;
    }

    /**
     * Gets the value of the assoccode property.
     * 
     * @return
     *     possible object is
     *     {@link ASSOCCODE }
     *     
     */
    public ASSOCCODE getASSOCCODE() {
        return assoccode;
    }

    /**
     * Sets the value of the assoccode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSOCCODE }
     *     
     */
    public void setASSOCCODE(ASSOCCODE value) {
        this.assoccode = value;
    }

    /**
     * Gets the value of the accessref property.
     * 
     * @return
     *     possible object is
     *     {@link ACCESSREF }
     *     
     */
    public ACCESSREF getACCESSREF() {
        return accessref;
    }

    /**
     * Sets the value of the accessref property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCESSREF }
     *     
     */
    public void setACCESSREF(ACCESSREF value) {
        this.accessref = value;
    }

    /**
     * Gets the value of the transfernumber property.
     * 
     * @return
     *     possible object is
     *     {@link TRANSFERNUMBER }
     *     
     */
    public TRANSFERNUMBER getTRANSFERNUMBER() {
        return transfernumber;
    }

    /**
     * Sets the value of the transfernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRANSFERNUMBER }
     *     
     */
    public void setTRANSFERNUMBER(TRANSFERNUMBER value) {
        this.transfernumber = value;
    }

    /**
     * Gets the value of the indicator property.
     * 
     * @return
     *     possible object is
     *     {@link INDICATOR }
     *     
     */
    public INDICATOR getINDICATOR() {
        return indicator;
    }

    /**
     * Sets the value of the indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDICATOR }
     *     
     */
    public void setINDICATOR(INDICATOR value) {
        this.indicator = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
