//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}INSTRUC_PARTICIPANT_SEND_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUC_PARTICIPANT_RECEIVE_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUCTION_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUCTION_CODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUCTION_CODE_LIST" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUCTION_CODE_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUCTION" minOccurs="0"/&gt;
 *         &lt;element ref="{}INSTRUCTION_STATUS" minOccurs="0"/&gt;
 *         &lt;element ref="{}NAME_PARTICIPANT" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACTION_REQUEST_INFORM" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instrucparticipantsendid",
    "instrucparticipantreceiveid",
    "instructionid",
    "instructioncode",
    "instructioncodelist",
    "instructioncodeagency",
    "instruction",
    "instructionstatus",
    "nameparticipant",
    "actionrequestinform"
})
@XmlRootElement(name = "E1VDEWINP")
public class E1VDEWINP {

    @XmlElement(name = "INSTRUC_PARTICIPANT_SEND_ID")
    protected INSTRUCPARTICIPANTSENDID instrucparticipantsendid;
    @XmlElement(name = "INSTRUC_PARTICIPANT_RECEIVE_ID")
    protected INSTRUCPARTICIPANTRECEIVEID instrucparticipantreceiveid;
    @XmlElement(name = "INSTRUCTION_ID")
    protected INSTRUCTIONID instructionid;
    @XmlElement(name = "INSTRUCTION_CODE")
    protected INSTRUCTIONCODE instructioncode;
    @XmlElement(name = "INSTRUCTION_CODE_LIST")
    protected INSTRUCTIONCODELIST instructioncodelist;
    @XmlElement(name = "INSTRUCTION_CODE_AGENCY")
    protected INSTRUCTIONCODEAGENCY instructioncodeagency;
    @XmlElement(name = "INSTRUCTION")
    protected INSTRUCTION instruction;
    @XmlElement(name = "INSTRUCTION_STATUS")
    protected INSTRUCTIONSTATUS instructionstatus;
    @XmlElement(name = "NAME_PARTICIPANT")
    protected NAMEPARTICIPANT nameparticipant;
    @XmlElement(name = "ACTION_REQUEST_INFORM")
    protected ACTIONREQUESTINFORM actionrequestinform;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the instrucparticipantsendid property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCPARTICIPANTSENDID }
     *     
     */
    public INSTRUCPARTICIPANTSENDID getINSTRUCPARTICIPANTSENDID() {
        return instrucparticipantsendid;
    }

    /**
     * Sets the value of the instrucparticipantsendid property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCPARTICIPANTSENDID }
     *     
     */
    public void setINSTRUCPARTICIPANTSENDID(INSTRUCPARTICIPANTSENDID value) {
        this.instrucparticipantsendid = value;
    }

    /**
     * Gets the value of the instrucparticipantreceiveid property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCPARTICIPANTRECEIVEID }
     *     
     */
    public INSTRUCPARTICIPANTRECEIVEID getINSTRUCPARTICIPANTRECEIVEID() {
        return instrucparticipantreceiveid;
    }

    /**
     * Sets the value of the instrucparticipantreceiveid property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCPARTICIPANTRECEIVEID }
     *     
     */
    public void setINSTRUCPARTICIPANTRECEIVEID(INSTRUCPARTICIPANTRECEIVEID value) {
        this.instrucparticipantreceiveid = value;
    }

    /**
     * Gets the value of the instructionid property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCTIONID }
     *     
     */
    public INSTRUCTIONID getINSTRUCTIONID() {
        return instructionid;
    }

    /**
     * Sets the value of the instructionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCTIONID }
     *     
     */
    public void setINSTRUCTIONID(INSTRUCTIONID value) {
        this.instructionid = value;
    }

    /**
     * Gets the value of the instructioncode property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCTIONCODE }
     *     
     */
    public INSTRUCTIONCODE getINSTRUCTIONCODE() {
        return instructioncode;
    }

    /**
     * Sets the value of the instructioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCTIONCODE }
     *     
     */
    public void setINSTRUCTIONCODE(INSTRUCTIONCODE value) {
        this.instructioncode = value;
    }

    /**
     * Gets the value of the instructioncodelist property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCTIONCODELIST }
     *     
     */
    public INSTRUCTIONCODELIST getINSTRUCTIONCODELIST() {
        return instructioncodelist;
    }

    /**
     * Sets the value of the instructioncodelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCTIONCODELIST }
     *     
     */
    public void setINSTRUCTIONCODELIST(INSTRUCTIONCODELIST value) {
        this.instructioncodelist = value;
    }

    /**
     * Gets the value of the instructioncodeagency property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCTIONCODEAGENCY }
     *     
     */
    public INSTRUCTIONCODEAGENCY getINSTRUCTIONCODEAGENCY() {
        return instructioncodeagency;
    }

    /**
     * Sets the value of the instructioncodeagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCTIONCODEAGENCY }
     *     
     */
    public void setINSTRUCTIONCODEAGENCY(INSTRUCTIONCODEAGENCY value) {
        this.instructioncodeagency = value;
    }

    /**
     * Gets the value of the instruction property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCTION }
     *     
     */
    public INSTRUCTION getINSTRUCTION() {
        return instruction;
    }

    /**
     * Sets the value of the instruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCTION }
     *     
     */
    public void setINSTRUCTION(INSTRUCTION value) {
        this.instruction = value;
    }

    /**
     * Gets the value of the instructionstatus property.
     * 
     * @return
     *     possible object is
     *     {@link INSTRUCTIONSTATUS }
     *     
     */
    public INSTRUCTIONSTATUS getINSTRUCTIONSTATUS() {
        return instructionstatus;
    }

    /**
     * Sets the value of the instructionstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTRUCTIONSTATUS }
     *     
     */
    public void setINSTRUCTIONSTATUS(INSTRUCTIONSTATUS value) {
        this.instructionstatus = value;
    }

    /**
     * Gets the value of the nameparticipant property.
     * 
     * @return
     *     possible object is
     *     {@link NAMEPARTICIPANT }
     *     
     */
    public NAMEPARTICIPANT getNAMEPARTICIPANT() {
        return nameparticipant;
    }

    /**
     * Sets the value of the nameparticipant property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAMEPARTICIPANT }
     *     
     */
    public void setNAMEPARTICIPANT(NAMEPARTICIPANT value) {
        this.nameparticipant = value;
    }

    /**
     * Gets the value of the actionrequestinform property.
     * 
     * @return
     *     possible object is
     *     {@link ACTIONREQUESTINFORM }
     *     
     */
    public ACTIONREQUESTINFORM getACTIONREQUESTINFORM() {
        return actionrequestinform;
    }

    /**
     * Sets the value of the actionrequestinform property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACTIONREQUESTINFORM }
     *     
     */
    public void setACTIONREQUESTINFORM(ACTIONREQUESTINFORM value) {
        this.actionrequestinform = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
