//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}MONETARY_AMOUNT_TYPE" minOccurs="0"/&gt;
 *         &lt;element ref="{}MONETARY_AMOUNT_VALUE" minOccurs="0"/&gt;
 *         &lt;element ref="{}CURRENCY_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}CURRENCY_QUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}STATUS" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWRFF_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWDTM_6" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "monetaryamounttype",
    "monetaryamountvalue",
    "currencyid",
    "currencyqualifier",
    "status",
    "e1VDEWRFF3",
    "e1VDEWDTM6"
})
@XmlRootElement(name = "E1VDEWMOA_6")
public class E1VDEWMOA6 {

    @XmlElement(name = "MONETARY_AMOUNT_TYPE")
    protected MONETARYAMOUNTTYPE monetaryamounttype;
    @XmlElement(name = "MONETARY_AMOUNT_VALUE")
    protected MONETARYAMOUNTVALUE monetaryamountvalue;
    @XmlElement(name = "CURRENCY_ID")
    protected CURRENCYID currencyid;
    @XmlElement(name = "CURRENCY_QUALIFIER")
    protected CURRENCYQUALIFIER currencyqualifier;
    @XmlElement(name = "STATUS")
    protected STATUS status;
    @XmlElement(name = "E1VDEWRFF_3")
    protected E1VDEWRFF3 e1VDEWRFF3;
    @XmlElement(name = "E1VDEWDTM_6")
    protected List<E1VDEWDTM6> e1VDEWDTM6;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the monetaryamounttype property.
     * 
     * @return
     *     possible object is
     *     {@link MONETARYAMOUNTTYPE }
     *     
     */
    public MONETARYAMOUNTTYPE getMONETARYAMOUNTTYPE() {
        return monetaryamounttype;
    }

    /**
     * Sets the value of the monetaryamounttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MONETARYAMOUNTTYPE }
     *     
     */
    public void setMONETARYAMOUNTTYPE(MONETARYAMOUNTTYPE value) {
        this.monetaryamounttype = value;
    }

    /**
     * Gets the value of the monetaryamountvalue property.
     * 
     * @return
     *     possible object is
     *     {@link MONETARYAMOUNTVALUE }
     *     
     */
    public MONETARYAMOUNTVALUE getMONETARYAMOUNTVALUE() {
        return monetaryamountvalue;
    }

    /**
     * Sets the value of the monetaryamountvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MONETARYAMOUNTVALUE }
     *     
     */
    public void setMONETARYAMOUNTVALUE(MONETARYAMOUNTVALUE value) {
        this.monetaryamountvalue = value;
    }

    /**
     * Gets the value of the currencyid property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCYID }
     *     
     */
    public CURRENCYID getCURRENCYID() {
        return currencyid;
    }

    /**
     * Sets the value of the currencyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCYID }
     *     
     */
    public void setCURRENCYID(CURRENCYID value) {
        this.currencyid = value;
    }

    /**
     * Gets the value of the currencyqualifier property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCYQUALIFIER }
     *     
     */
    public CURRENCYQUALIFIER getCURRENCYQUALIFIER() {
        return currencyqualifier;
    }

    /**
     * Sets the value of the currencyqualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCYQUALIFIER }
     *     
     */
    public void setCURRENCYQUALIFIER(CURRENCYQUALIFIER value) {
        this.currencyqualifier = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link STATUS }
     *     
     */
    public STATUS getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link STATUS }
     *     
     */
    public void setSTATUS(STATUS value) {
        this.status = value;
    }

    /**
     * Gets the value of the e1VDEWRFF3 property.
     * 
     * @return
     *     possible object is
     *     {@link E1VDEWRFF3 }
     *     
     */
    public E1VDEWRFF3 getE1VDEWRFF3() {
        return e1VDEWRFF3;
    }

    /**
     * Sets the value of the e1VDEWRFF3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link E1VDEWRFF3 }
     *     
     */
    public void setE1VDEWRFF3(E1VDEWRFF3 value) {
        this.e1VDEWRFF3 = value;
    }

    /**
     * Gets the value of the e1VDEWDTM6 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWDTM6 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWDTM6().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWDTM6 }
     * 
     * 
     */
    public List<E1VDEWDTM6> getE1VDEWDTM6() {
        if (e1VDEWDTM6 == null) {
            e1VDEWDTM6 = new ArrayList<E1VDEWDTM6>();
        }
        return this.e1VDEWDTM6;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
