//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}CONTACTFUNC" minOccurs="0"/&gt;
 *         &lt;element ref="{}CONTACTID" minOccurs="0"/&gt;
 *         &lt;element ref="{}CONTACTNAME" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWCOM" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactfunc",
    "contactid",
    "contactname",
    "e1VDEWCOM"
})
@XmlRootElement(name = "E1VDEWCTA")
public class E1VDEWCTA {

    @XmlElement(name = "CONTACTFUNC")
    protected CONTACTFUNC contactfunc;
    @XmlElement(name = "CONTACTID")
    protected CONTACTID contactid;
    @XmlElement(name = "CONTACTNAME")
    protected CONTACTNAME contactname;
    @XmlElement(name = "E1VDEWCOM")
    protected List<E1VDEWCOM> e1VDEWCOM;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the contactfunc property.
     * 
     * @return
     *     possible object is
     *     {@link CONTACTFUNC }
     *     
     */
    public CONTACTFUNC getCONTACTFUNC() {
        return contactfunc;
    }

    /**
     * Sets the value of the contactfunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTACTFUNC }
     *     
     */
    public void setCONTACTFUNC(CONTACTFUNC value) {
        this.contactfunc = value;
    }

    /**
     * Gets the value of the contactid property.
     * 
     * @return
     *     possible object is
     *     {@link CONTACTID }
     *     
     */
    public CONTACTID getCONTACTID() {
        return contactid;
    }

    /**
     * Sets the value of the contactid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTACTID }
     *     
     */
    public void setCONTACTID(CONTACTID value) {
        this.contactid = value;
    }

    /**
     * Gets the value of the contactname property.
     * 
     * @return
     *     possible object is
     *     {@link CONTACTNAME }
     *     
     */
    public CONTACTNAME getCONTACTNAME() {
        return contactname;
    }

    /**
     * Sets the value of the contactname property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTACTNAME }
     *     
     */
    public void setCONTACTNAME(CONTACTNAME value) {
        this.contactname = value;
    }

    /**
     * Gets the value of the e1VDEWCOM property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWCOM property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWCOM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWCOM }
     * 
     * 
     */
    public List<E1VDEWCOM> getE1VDEWCOM() {
        if (e1VDEWCOM == null) {
            e1VDEWCOM = new ArrayList<E1VDEWCOM>();
        }
        return this.e1VDEWCOM;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
