//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PARTY_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_NUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_HOLDER_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_HOLDER_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_CURRENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_CODE_LIST_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_RESP_AGENCY_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_BRANCH" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_CODE_LIST_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_RESP_AGENCY_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_NAME" minOccurs="0"/&gt;
 *         &lt;element ref="{}BANK_BRANCH_PLACE" minOccurs="0"/&gt;
 *         &lt;element ref="{}COUNTRY" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partyid",
    "accountnumber",
    "accountholder1",
    "accountholder2",
    "accountcurrency",
    "bankid",
    "bankcodelist1",
    "bankrespagency1",
    "bankbranch",
    "bankcodelist2",
    "bankrespagency2",
    "bankname",
    "bankbranchplace",
    "country"
})
@XmlRootElement(name = "E1VDEWFII_4")
public class E1VDEWFII4 {

    @XmlElement(name = "PARTY_ID")
    protected PARTYID partyid;
    @XmlElement(name = "ACCOUNT_NUMBER")
    protected ACCOUNTNUMBER accountnumber;
    @XmlElement(name = "ACCOUNT_HOLDER_1")
    protected ACCOUNTHOLDER1 accountholder1;
    @XmlElement(name = "ACCOUNT_HOLDER_2")
    protected ACCOUNTHOLDER2 accountholder2;
    @XmlElement(name = "ACCOUNT_CURRENCY")
    protected ACCOUNTCURRENCY accountcurrency;
    @XmlElement(name = "BANK_ID")
    protected BANKID bankid;
    @XmlElement(name = "BANK_CODE_LIST_1")
    protected BANKCODELIST1 bankcodelist1;
    @XmlElement(name = "BANK_RESP_AGENCY_1")
    protected BANKRESPAGENCY1 bankrespagency1;
    @XmlElement(name = "BANK_BRANCH")
    protected BANKBRANCH bankbranch;
    @XmlElement(name = "BANK_CODE_LIST_2")
    protected BANKCODELIST2 bankcodelist2;
    @XmlElement(name = "BANK_RESP_AGENCY_2")
    protected BANKRESPAGENCY2 bankrespagency2;
    @XmlElement(name = "BANK_NAME")
    protected BANKNAME bankname;
    @XmlElement(name = "BANK_BRANCH_PLACE")
    protected BANKBRANCHPLACE bankbranchplace;
    @XmlElement(name = "COUNTRY")
    protected COUNTRY country;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the partyid property.
     * 
     * @return
     *     possible object is
     *     {@link PARTYID }
     *     
     */
    public PARTYID getPARTYID() {
        return partyid;
    }

    /**
     * Sets the value of the partyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTYID }
     *     
     */
    public void setPARTYID(PARTYID value) {
        this.partyid = value;
    }

    /**
     * Gets the value of the accountnumber property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTNUMBER }
     *     
     */
    public ACCOUNTNUMBER getACCOUNTNUMBER() {
        return accountnumber;
    }

    /**
     * Sets the value of the accountnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTNUMBER }
     *     
     */
    public void setACCOUNTNUMBER(ACCOUNTNUMBER value) {
        this.accountnumber = value;
    }

    /**
     * Gets the value of the accountholder1 property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTHOLDER1 }
     *     
     */
    public ACCOUNTHOLDER1 getACCOUNTHOLDER1() {
        return accountholder1;
    }

    /**
     * Sets the value of the accountholder1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTHOLDER1 }
     *     
     */
    public void setACCOUNTHOLDER1(ACCOUNTHOLDER1 value) {
        this.accountholder1 = value;
    }

    /**
     * Gets the value of the accountholder2 property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTHOLDER2 }
     *     
     */
    public ACCOUNTHOLDER2 getACCOUNTHOLDER2() {
        return accountholder2;
    }

    /**
     * Sets the value of the accountholder2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTHOLDER2 }
     *     
     */
    public void setACCOUNTHOLDER2(ACCOUNTHOLDER2 value) {
        this.accountholder2 = value;
    }

    /**
     * Gets the value of the accountcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTCURRENCY }
     *     
     */
    public ACCOUNTCURRENCY getACCOUNTCURRENCY() {
        return accountcurrency;
    }

    /**
     * Sets the value of the accountcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTCURRENCY }
     *     
     */
    public void setACCOUNTCURRENCY(ACCOUNTCURRENCY value) {
        this.accountcurrency = value;
    }

    /**
     * Gets the value of the bankid property.
     * 
     * @return
     *     possible object is
     *     {@link BANKID }
     *     
     */
    public BANKID getBANKID() {
        return bankid;
    }

    /**
     * Sets the value of the bankid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKID }
     *     
     */
    public void setBANKID(BANKID value) {
        this.bankid = value;
    }

    /**
     * Gets the value of the bankcodelist1 property.
     * 
     * @return
     *     possible object is
     *     {@link BANKCODELIST1 }
     *     
     */
    public BANKCODELIST1 getBANKCODELIST1() {
        return bankcodelist1;
    }

    /**
     * Sets the value of the bankcodelist1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKCODELIST1 }
     *     
     */
    public void setBANKCODELIST1(BANKCODELIST1 value) {
        this.bankcodelist1 = value;
    }

    /**
     * Gets the value of the bankrespagency1 property.
     * 
     * @return
     *     possible object is
     *     {@link BANKRESPAGENCY1 }
     *     
     */
    public BANKRESPAGENCY1 getBANKRESPAGENCY1() {
        return bankrespagency1;
    }

    /**
     * Sets the value of the bankrespagency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKRESPAGENCY1 }
     *     
     */
    public void setBANKRESPAGENCY1(BANKRESPAGENCY1 value) {
        this.bankrespagency1 = value;
    }

    /**
     * Gets the value of the bankbranch property.
     * 
     * @return
     *     possible object is
     *     {@link BANKBRANCH }
     *     
     */
    public BANKBRANCH getBANKBRANCH() {
        return bankbranch;
    }

    /**
     * Sets the value of the bankbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKBRANCH }
     *     
     */
    public void setBANKBRANCH(BANKBRANCH value) {
        this.bankbranch = value;
    }

    /**
     * Gets the value of the bankcodelist2 property.
     * 
     * @return
     *     possible object is
     *     {@link BANKCODELIST2 }
     *     
     */
    public BANKCODELIST2 getBANKCODELIST2() {
        return bankcodelist2;
    }

    /**
     * Sets the value of the bankcodelist2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKCODELIST2 }
     *     
     */
    public void setBANKCODELIST2(BANKCODELIST2 value) {
        this.bankcodelist2 = value;
    }

    /**
     * Gets the value of the bankrespagency2 property.
     * 
     * @return
     *     possible object is
     *     {@link BANKRESPAGENCY2 }
     *     
     */
    public BANKRESPAGENCY2 getBANKRESPAGENCY2() {
        return bankrespagency2;
    }

    /**
     * Sets the value of the bankrespagency2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKRESPAGENCY2 }
     *     
     */
    public void setBANKRESPAGENCY2(BANKRESPAGENCY2 value) {
        this.bankrespagency2 = value;
    }

    /**
     * Gets the value of the bankname property.
     * 
     * @return
     *     possible object is
     *     {@link BANKNAME }
     *     
     */
    public BANKNAME getBANKNAME() {
        return bankname;
    }

    /**
     * Sets the value of the bankname property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKNAME }
     *     
     */
    public void setBANKNAME(BANKNAME value) {
        this.bankname = value;
    }

    /**
     * Gets the value of the bankbranchplace property.
     * 
     * @return
     *     possible object is
     *     {@link BANKBRANCHPLACE }
     *     
     */
    public BANKBRANCHPLACE getBANKBRANCHPLACE() {
        return bankbranchplace;
    }

    /**
     * Sets the value of the bankbranchplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BANKBRANCHPLACE }
     *     
     */
    public void setBANKBRANCHPLACE(BANKBRANCHPLACE value) {
        this.bankbranchplace = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link COUNTRY }
     *     
     */
    public COUNTRY getCOUNTRY() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link COUNTRY }
     *     
     */
    public void setCOUNTRY(COUNTRY value) {
        this.country = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
