//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}TEXT_SUBJECT_QUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}TEXT_FUNCTION_CODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}FREE_TEXT_CODE" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}FREE_TEXT_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}FREE_TEXT_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}FREE_TEXT_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}FREE_TEXT_4" minOccurs="0"/&gt;
 *         &lt;element ref="{}FREE_TEXT_5" minOccurs="0"/&gt;
 *         &lt;element ref="{}LANGUAGE" minOccurs="0"/&gt;
 *         &lt;element ref="{}TEXT_FORMAT" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textsubjectqualifier",
    "textfunctioncode",
    "freetextcode",
    "codelistqualifier",
    "codelistresponsibleagency",
    "freetext1",
    "freetext2",
    "freetext3",
    "freetext4",
    "freetext5",
    "language",
    "textformat"
})
@XmlRootElement(name = "E1VDEWFTX_2")
public class E1VDEWFTX2 {

    @XmlElement(name = "TEXT_SUBJECT_QUALIFIER")
    protected TEXTSUBJECTQUALIFIER textsubjectqualifier;
    @XmlElement(name = "TEXT_FUNCTION_CODE")
    protected TEXTFUNCTIONCODE textfunctioncode;
    @XmlElement(name = "FREE_TEXT_CODE")
    protected FREETEXTCODE freetextcode;
    @XmlElement(name = "CODE_LIST_QUALIFIER")
    protected CODELISTQUALIFIER codelistqualifier;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY")
    protected CODELISTRESPONSIBLEAGENCY codelistresponsibleagency;
    @XmlElement(name = "FREE_TEXT_1")
    protected FREETEXT1 freetext1;
    @XmlElement(name = "FREE_TEXT_2")
    protected FREETEXT2 freetext2;
    @XmlElement(name = "FREE_TEXT_3")
    protected FREETEXT3 freetext3;
    @XmlElement(name = "FREE_TEXT_4")
    protected FREETEXT4 freetext4;
    @XmlElement(name = "FREE_TEXT_5")
    protected FREETEXT5 freetext5;
    @XmlElement(name = "LANGUAGE")
    protected LANGUAGE language;
    @XmlElement(name = "TEXT_FORMAT")
    protected TEXTFORMAT textformat;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the textsubjectqualifier property.
     * 
     * @return
     *     possible object is
     *     {@link TEXTSUBJECTQUALIFIER }
     *     
     */
    public TEXTSUBJECTQUALIFIER getTEXTSUBJECTQUALIFIER() {
        return textsubjectqualifier;
    }

    /**
     * Sets the value of the textsubjectqualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEXTSUBJECTQUALIFIER }
     *     
     */
    public void setTEXTSUBJECTQUALIFIER(TEXTSUBJECTQUALIFIER value) {
        this.textsubjectqualifier = value;
    }

    /**
     * Gets the value of the textfunctioncode property.
     * 
     * @return
     *     possible object is
     *     {@link TEXTFUNCTIONCODE }
     *     
     */
    public TEXTFUNCTIONCODE getTEXTFUNCTIONCODE() {
        return textfunctioncode;
    }

    /**
     * Sets the value of the textfunctioncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEXTFUNCTIONCODE }
     *     
     */
    public void setTEXTFUNCTIONCODE(TEXTFUNCTIONCODE value) {
        this.textfunctioncode = value;
    }

    /**
     * Gets the value of the freetextcode property.
     * 
     * @return
     *     possible object is
     *     {@link FREETEXTCODE }
     *     
     */
    public FREETEXTCODE getFREETEXTCODE() {
        return freetextcode;
    }

    /**
     * Sets the value of the freetextcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREETEXTCODE }
     *     
     */
    public void setFREETEXTCODE(FREETEXTCODE value) {
        this.freetextcode = value;
    }

    /**
     * Gets the value of the codelistqualifier property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER }
     *     
     */
    public CODELISTQUALIFIER getCODELISTQUALIFIER() {
        return codelistqualifier;
    }

    /**
     * Sets the value of the codelistqualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER }
     *     
     */
    public void setCODELISTQUALIFIER(CODELISTQUALIFIER value) {
        this.codelistqualifier = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY getCODELISTRESPONSIBLEAGENCY() {
        return codelistresponsibleagency;
    }

    /**
     * Sets the value of the codelistresponsibleagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY(CODELISTRESPONSIBLEAGENCY value) {
        this.codelistresponsibleagency = value;
    }

    /**
     * Gets the value of the freetext1 property.
     * 
     * @return
     *     possible object is
     *     {@link FREETEXT1 }
     *     
     */
    public FREETEXT1 getFREETEXT1() {
        return freetext1;
    }

    /**
     * Sets the value of the freetext1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREETEXT1 }
     *     
     */
    public void setFREETEXT1(FREETEXT1 value) {
        this.freetext1 = value;
    }

    /**
     * Gets the value of the freetext2 property.
     * 
     * @return
     *     possible object is
     *     {@link FREETEXT2 }
     *     
     */
    public FREETEXT2 getFREETEXT2() {
        return freetext2;
    }

    /**
     * Sets the value of the freetext2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREETEXT2 }
     *     
     */
    public void setFREETEXT2(FREETEXT2 value) {
        this.freetext2 = value;
    }

    /**
     * Gets the value of the freetext3 property.
     * 
     * @return
     *     possible object is
     *     {@link FREETEXT3 }
     *     
     */
    public FREETEXT3 getFREETEXT3() {
        return freetext3;
    }

    /**
     * Sets the value of the freetext3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREETEXT3 }
     *     
     */
    public void setFREETEXT3(FREETEXT3 value) {
        this.freetext3 = value;
    }

    /**
     * Gets the value of the freetext4 property.
     * 
     * @return
     *     possible object is
     *     {@link FREETEXT4 }
     *     
     */
    public FREETEXT4 getFREETEXT4() {
        return freetext4;
    }

    /**
     * Sets the value of the freetext4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREETEXT4 }
     *     
     */
    public void setFREETEXT4(FREETEXT4 value) {
        this.freetext4 = value;
    }

    /**
     * Gets the value of the freetext5 property.
     * 
     * @return
     *     possible object is
     *     {@link FREETEXT5 }
     *     
     */
    public FREETEXT5 getFREETEXT5() {
        return freetext5;
    }

    /**
     * Sets the value of the freetext5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FREETEXT5 }
     *     
     */
    public void setFREETEXT5(FREETEXT5 value) {
        this.freetext5 = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LANGUAGE }
     *     
     */
    public LANGUAGE getLANGUAGE() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LANGUAGE }
     *     
     */
    public void setLANGUAGE(LANGUAGE value) {
        this.language = value;
    }

    /**
     * Gets the value of the textformat property.
     * 
     * @return
     *     possible object is
     *     {@link TEXTFORMAT }
     *     
     */
    public TEXTFORMAT getTEXTFORMAT() {
        return textformat;
    }

    /**
     * Sets the value of the textformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEXTFORMAT }
     *     
     */
    public void setTEXTFORMAT(TEXTFORMAT value) {
        this.textformat = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
