//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PROPERTY_CLASS" minOccurs="0"/&gt;
 *         &lt;element ref="{}PROPERTY_MEASURE" minOccurs="0"/&gt;
 *         &lt;element ref="{}MEASUREMENT_SIGNIFICANCE" minOccurs="0"/&gt;
 *         &lt;element ref="{}MEASUREMENT_ATTRIBUTE_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}MEASUREMENT_ATTRIBUTE" minOccurs="0"/&gt;
 *         &lt;element ref="{}CHARACTERISTIC_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}CHARACTERISTIC_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}CHARACTERISTIC_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}E1VDEWCAV_3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "propertyclass",
    "propertymeasure",
    "measurementsignificance",
    "measurementattributeid",
    "measurementattribute",
    "characteristicid",
    "codelistqualifier",
    "codelistresponsibleagency",
    "characteristic1",
    "characteristic2",
    "e1VDEWCAV3"
})
@XmlRootElement(name = "E1VDEWCCI_3")
public class E1VDEWCCI3 {

    @XmlElement(name = "PROPERTY_CLASS")
    protected PROPERTYCLASS propertyclass;
    @XmlElement(name = "PROPERTY_MEASURE")
    protected PROPERTYMEASURE propertymeasure;
    @XmlElement(name = "MEASUREMENT_SIGNIFICANCE")
    protected MEASUREMENTSIGNIFICANCE measurementsignificance;
    @XmlElement(name = "MEASUREMENT_ATTRIBUTE_ID")
    protected MEASUREMENTATTRIBUTEID measurementattributeid;
    @XmlElement(name = "MEASUREMENT_ATTRIBUTE")
    protected MEASUREMENTATTRIBUTE measurementattribute;
    @XmlElement(name = "CHARACTERISTIC_ID")
    protected CHARACTERISTICID characteristicid;
    @XmlElement(name = "CODE_LIST_QUALIFIER")
    protected CODELISTQUALIFIER codelistqualifier;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY")
    protected CODELISTRESPONSIBLEAGENCY codelistresponsibleagency;
    @XmlElement(name = "CHARACTERISTIC_1")
    protected CHARACTERISTIC1 characteristic1;
    @XmlElement(name = "CHARACTERISTIC_2")
    protected CHARACTERISTIC2 characteristic2;
    @XmlElement(name = "E1VDEWCAV_3")
    protected List<E1VDEWCAV3> e1VDEWCAV3;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the propertyclass property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTYCLASS }
     *     
     */
    public PROPERTYCLASS getPROPERTYCLASS() {
        return propertyclass;
    }

    /**
     * Sets the value of the propertyclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTYCLASS }
     *     
     */
    public void setPROPERTYCLASS(PROPERTYCLASS value) {
        this.propertyclass = value;
    }

    /**
     * Gets the value of the propertymeasure property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTYMEASURE }
     *     
     */
    public PROPERTYMEASURE getPROPERTYMEASURE() {
        return propertymeasure;
    }

    /**
     * Sets the value of the propertymeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTYMEASURE }
     *     
     */
    public void setPROPERTYMEASURE(PROPERTYMEASURE value) {
        this.propertymeasure = value;
    }

    /**
     * Gets the value of the measurementsignificance property.
     * 
     * @return
     *     possible object is
     *     {@link MEASUREMENTSIGNIFICANCE }
     *     
     */
    public MEASUREMENTSIGNIFICANCE getMEASUREMENTSIGNIFICANCE() {
        return measurementsignificance;
    }

    /**
     * Sets the value of the measurementsignificance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEASUREMENTSIGNIFICANCE }
     *     
     */
    public void setMEASUREMENTSIGNIFICANCE(MEASUREMENTSIGNIFICANCE value) {
        this.measurementsignificance = value;
    }

    /**
     * Gets the value of the measurementattributeid property.
     * 
     * @return
     *     possible object is
     *     {@link MEASUREMENTATTRIBUTEID }
     *     
     */
    public MEASUREMENTATTRIBUTEID getMEASUREMENTATTRIBUTEID() {
        return measurementattributeid;
    }

    /**
     * Sets the value of the measurementattributeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEASUREMENTATTRIBUTEID }
     *     
     */
    public void setMEASUREMENTATTRIBUTEID(MEASUREMENTATTRIBUTEID value) {
        this.measurementattributeid = value;
    }

    /**
     * Gets the value of the measurementattribute property.
     * 
     * @return
     *     possible object is
     *     {@link MEASUREMENTATTRIBUTE }
     *     
     */
    public MEASUREMENTATTRIBUTE getMEASUREMENTATTRIBUTE() {
        return measurementattribute;
    }

    /**
     * Sets the value of the measurementattribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEASUREMENTATTRIBUTE }
     *     
     */
    public void setMEASUREMENTATTRIBUTE(MEASUREMENTATTRIBUTE value) {
        this.measurementattribute = value;
    }

    /**
     * Gets the value of the characteristicid property.
     * 
     * @return
     *     possible object is
     *     {@link CHARACTERISTICID }
     *     
     */
    public CHARACTERISTICID getCHARACTERISTICID() {
        return characteristicid;
    }

    /**
     * Sets the value of the characteristicid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHARACTERISTICID }
     *     
     */
    public void setCHARACTERISTICID(CHARACTERISTICID value) {
        this.characteristicid = value;
    }

    /**
     * Gets the value of the codelistqualifier property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER }
     *     
     */
    public CODELISTQUALIFIER getCODELISTQUALIFIER() {
        return codelistqualifier;
    }

    /**
     * Sets the value of the codelistqualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER }
     *     
     */
    public void setCODELISTQUALIFIER(CODELISTQUALIFIER value) {
        this.codelistqualifier = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY getCODELISTRESPONSIBLEAGENCY() {
        return codelistresponsibleagency;
    }

    /**
     * Sets the value of the codelistresponsibleagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY(CODELISTRESPONSIBLEAGENCY value) {
        this.codelistresponsibleagency = value;
    }

    /**
     * Gets the value of the characteristic1 property.
     * 
     * @return
     *     possible object is
     *     {@link CHARACTERISTIC1 }
     *     
     */
    public CHARACTERISTIC1 getCHARACTERISTIC1() {
        return characteristic1;
    }

    /**
     * Sets the value of the characteristic1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHARACTERISTIC1 }
     *     
     */
    public void setCHARACTERISTIC1(CHARACTERISTIC1 value) {
        this.characteristic1 = value;
    }

    /**
     * Gets the value of the characteristic2 property.
     * 
     * @return
     *     possible object is
     *     {@link CHARACTERISTIC2 }
     *     
     */
    public CHARACTERISTIC2 getCHARACTERISTIC2() {
        return characteristic2;
    }

    /**
     * Sets the value of the characteristic2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHARACTERISTIC2 }
     *     
     */
    public void setCHARACTERISTIC2(CHARACTERISTIC2 value) {
        this.characteristic2 = value;
    }

    /**
     * Gets the value of the e1VDEWCAV3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1VDEWCAV3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1VDEWCAV3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link E1VDEWCAV3 }
     * 
     * 
     */
    public List<E1VDEWCAV3> getE1VDEWCAV3() {
        if (e1VDEWCAV3 == null) {
            e1VDEWCAV3 = new ArrayList<E1VDEWCAV3>();
        }
        return this.e1VDEWCAV3;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
