//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}REFERENCEQUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}REFERENCENUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}LINENUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}VERSIONNUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}REVISION" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referencequalifier",
    "referencenumber",
    "linenumber",
    "versionnumber",
    "revision"
})
@XmlRootElement(name = "E1VDEWRFF_4")
public class E1VDEWRFF4 {

    @XmlElement(name = "REFERENCEQUALIFIER")
    protected REFERENCEQUALIFIER referencequalifier;
    @XmlElement(name = "REFERENCENUMBER")
    protected REFERENCENUMBER referencenumber;
    @XmlElement(name = "LINENUMBER")
    protected LINENUMBER linenumber;
    @XmlElement(name = "VERSIONNUMBER")
    protected VERSIONNUMBER versionnumber;
    @XmlElement(name = "REVISION")
    protected REVISION revision;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the referencequalifier property.
     * 
     * @return
     *     possible object is
     *     {@link REFERENCEQUALIFIER }
     *     
     */
    public REFERENCEQUALIFIER getREFERENCEQUALIFIER() {
        return referencequalifier;
    }

    /**
     * Sets the value of the referencequalifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link REFERENCEQUALIFIER }
     *     
     */
    public void setREFERENCEQUALIFIER(REFERENCEQUALIFIER value) {
        this.referencequalifier = value;
    }

    /**
     * Gets the value of the referencenumber property.
     * 
     * @return
     *     possible object is
     *     {@link REFERENCENUMBER }
     *     
     */
    public REFERENCENUMBER getREFERENCENUMBER() {
        return referencenumber;
    }

    /**
     * Sets the value of the referencenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link REFERENCENUMBER }
     *     
     */
    public void setREFERENCENUMBER(REFERENCENUMBER value) {
        this.referencenumber = value;
    }

    /**
     * Gets the value of the linenumber property.
     * 
     * @return
     *     possible object is
     *     {@link LINENUMBER }
     *     
     */
    public LINENUMBER getLINENUMBER() {
        return linenumber;
    }

    /**
     * Sets the value of the linenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link LINENUMBER }
     *     
     */
    public void setLINENUMBER(LINENUMBER value) {
        this.linenumber = value;
    }

    /**
     * Gets the value of the versionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link VERSIONNUMBER }
     *     
     */
    public VERSIONNUMBER getVERSIONNUMBER() {
        return versionnumber;
    }

    /**
     * Sets the value of the versionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link VERSIONNUMBER }
     *     
     */
    public void setVERSIONNUMBER(VERSIONNUMBER value) {
        this.versionnumber = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link REVISION }
     *     
     */
    public REVISION getREVISION() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link REVISION }
     *     
     */
    public void setREVISION(REVISION value) {
        this.revision = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
