//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DATUMQUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}DATUM" minOccurs="0"/&gt;
 *         &lt;element ref="{}FORMAT" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumqualifier",
    "datum",
    "format"
})
@XmlRootElement(name = "E1VDEWDTM_3")
public class E1VDEWDTM3 {

    @XmlElement(name = "DATUMQUALIFIER")
    protected DATUMQUALIFIER datumqualifier;
    @XmlElement(name = "DATUM")
    protected DATUM datum;
    @XmlElement(name = "FORMAT")
    protected FORMAT format;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the datumqualifier property.
     * 
     * @return
     *     possible object is
     *     {@link DATUMQUALIFIER }
     *     
     */
    public DATUMQUALIFIER getDATUMQUALIFIER() {
        return datumqualifier;
    }

    /**
     * Sets the value of the datumqualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATUMQUALIFIER }
     *     
     */
    public void setDATUMQUALIFIER(DATUMQUALIFIER value) {
        this.datumqualifier = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link DATUM }
     *     
     */
    public DATUM getDATUM() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATUM }
     *     
     */
    public void setDATUM(DATUM value) {
        this.datum = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link FORMAT }
     *     
     */
    public FORMAT getFORMAT() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link FORMAT }
     *     
     */
    public void setFORMAT(FORMAT value) {
        this.format = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
