//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DTF_FUNCTION" minOccurs="0"/&gt;
 *         &lt;element ref="{}TYPE_CODED" minOccurs="0"/&gt;
 *         &lt;element ref="{}TYPE_CODE_LIST" minOccurs="0"/&gt;
 *         &lt;element ref="{}TYPE_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}TYPE" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_CODE_LIST" minOccurs="0"/&gt;
 *         &lt;element ref="{}ACCOUNT_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}ASSESSMENT_BASIS" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_RATE_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_CODE_LIST_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_AGENCY_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_RATE" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_RATE_BASIS" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_CODE_LIST_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}DETAIL_AGENCY_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}CATEGORY" minOccurs="0"/&gt;
 *         &lt;element ref="{}PARTY_TAX_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}CALCULATION_SEQUENCE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dtffunction",
    "typecoded",
    "typecodelist",
    "typeagency",
    "type",
    "accountid",
    "accountcodelist",
    "accountagency",
    "assessmentbasis",
    "detailrateid",
    "detailcodelist1",
    "detailagency1",
    "detailrate",
    "detailratebasis",
    "detailcodelist2",
    "detailagency2",
    "category",
    "partytaxid",
    "calculationsequence"
})
@XmlRootElement(name = "E1VDEWTAX_3")
public class E1VDEWTAX3 {

    @XmlElement(name = "DTF_FUNCTION")
    protected DTFFUNCTION dtffunction;
    @XmlElement(name = "TYPE_CODED")
    protected TYPECODED typecoded;
    @XmlElement(name = "TYPE_CODE_LIST")
    protected TYPECODELIST typecodelist;
    @XmlElement(name = "TYPE_AGENCY")
    protected TYPEAGENCY typeagency;
    @XmlElement(name = "TYPE")
    protected TYPE type;
    @XmlElement(name = "ACCOUNT_ID")
    protected ACCOUNTID accountid;
    @XmlElement(name = "ACCOUNT_CODE_LIST")
    protected ACCOUNTCODELIST accountcodelist;
    @XmlElement(name = "ACCOUNT_AGENCY")
    protected ACCOUNTAGENCY accountagency;
    @XmlElement(name = "ASSESSMENT_BASIS")
    protected ASSESSMENTBASIS assessmentbasis;
    @XmlElement(name = "DETAIL_RATE_ID")
    protected DETAILRATEID detailrateid;
    @XmlElement(name = "DETAIL_CODE_LIST_1")
    protected DETAILCODELIST1 detailcodelist1;
    @XmlElement(name = "DETAIL_AGENCY_1")
    protected DETAILAGENCY1 detailagency1;
    @XmlElement(name = "DETAIL_RATE")
    protected DETAILRATE detailrate;
    @XmlElement(name = "DETAIL_RATE_BASIS")
    protected DETAILRATEBASIS detailratebasis;
    @XmlElement(name = "DETAIL_CODE_LIST_2")
    protected DETAILCODELIST2 detailcodelist2;
    @XmlElement(name = "DETAIL_AGENCY_2")
    protected DETAILAGENCY2 detailagency2;
    @XmlElement(name = "CATEGORY")
    protected CATEGORY category;
    @XmlElement(name = "PARTY_TAX_ID")
    protected PARTYTAXID partytaxid;
    @XmlElement(name = "CALCULATION_SEQUENCE")
    protected CALCULATIONSEQUENCE calculationsequence;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the dtffunction property.
     * 
     * @return
     *     possible object is
     *     {@link DTFFUNCTION }
     *     
     */
    public DTFFUNCTION getDTFFUNCTION() {
        return dtffunction;
    }

    /**
     * Sets the value of the dtffunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTFFUNCTION }
     *     
     */
    public void setDTFFUNCTION(DTFFUNCTION value) {
        this.dtffunction = value;
    }

    /**
     * Gets the value of the typecoded property.
     * 
     * @return
     *     possible object is
     *     {@link TYPECODED }
     *     
     */
    public TYPECODED getTYPECODED() {
        return typecoded;
    }

    /**
     * Sets the value of the typecoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPECODED }
     *     
     */
    public void setTYPECODED(TYPECODED value) {
        this.typecoded = value;
    }

    /**
     * Gets the value of the typecodelist property.
     * 
     * @return
     *     possible object is
     *     {@link TYPECODELIST }
     *     
     */
    public TYPECODELIST getTYPECODELIST() {
        return typecodelist;
    }

    /**
     * Sets the value of the typecodelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPECODELIST }
     *     
     */
    public void setTYPECODELIST(TYPECODELIST value) {
        this.typecodelist = value;
    }

    /**
     * Gets the value of the typeagency property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEAGENCY }
     *     
     */
    public TYPEAGENCY getTYPEAGENCY() {
        return typeagency;
    }

    /**
     * Sets the value of the typeagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEAGENCY }
     *     
     */
    public void setTYPEAGENCY(TYPEAGENCY value) {
        this.typeagency = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TYPE }
     *     
     */
    public TYPE getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPE }
     *     
     */
    public void setTYPE(TYPE value) {
        this.type = value;
    }

    /**
     * Gets the value of the accountid property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTID }
     *     
     */
    public ACCOUNTID getACCOUNTID() {
        return accountid;
    }

    /**
     * Sets the value of the accountid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTID }
     *     
     */
    public void setACCOUNTID(ACCOUNTID value) {
        this.accountid = value;
    }

    /**
     * Gets the value of the accountcodelist property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTCODELIST }
     *     
     */
    public ACCOUNTCODELIST getACCOUNTCODELIST() {
        return accountcodelist;
    }

    /**
     * Sets the value of the accountcodelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTCODELIST }
     *     
     */
    public void setACCOUNTCODELIST(ACCOUNTCODELIST value) {
        this.accountcodelist = value;
    }

    /**
     * Gets the value of the accountagency property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTAGENCY }
     *     
     */
    public ACCOUNTAGENCY getACCOUNTAGENCY() {
        return accountagency;
    }

    /**
     * Sets the value of the accountagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTAGENCY }
     *     
     */
    public void setACCOUNTAGENCY(ACCOUNTAGENCY value) {
        this.accountagency = value;
    }

    /**
     * Gets the value of the assessmentbasis property.
     * 
     * @return
     *     possible object is
     *     {@link ASSESSMENTBASIS }
     *     
     */
    public ASSESSMENTBASIS getASSESSMENTBASIS() {
        return assessmentbasis;
    }

    /**
     * Sets the value of the assessmentbasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSESSMENTBASIS }
     *     
     */
    public void setASSESSMENTBASIS(ASSESSMENTBASIS value) {
        this.assessmentbasis = value;
    }

    /**
     * Gets the value of the detailrateid property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILRATEID }
     *     
     */
    public DETAILRATEID getDETAILRATEID() {
        return detailrateid;
    }

    /**
     * Sets the value of the detailrateid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILRATEID }
     *     
     */
    public void setDETAILRATEID(DETAILRATEID value) {
        this.detailrateid = value;
    }

    /**
     * Gets the value of the detailcodelist1 property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILCODELIST1 }
     *     
     */
    public DETAILCODELIST1 getDETAILCODELIST1() {
        return detailcodelist1;
    }

    /**
     * Sets the value of the detailcodelist1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILCODELIST1 }
     *     
     */
    public void setDETAILCODELIST1(DETAILCODELIST1 value) {
        this.detailcodelist1 = value;
    }

    /**
     * Gets the value of the detailagency1 property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILAGENCY1 }
     *     
     */
    public DETAILAGENCY1 getDETAILAGENCY1() {
        return detailagency1;
    }

    /**
     * Sets the value of the detailagency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILAGENCY1 }
     *     
     */
    public void setDETAILAGENCY1(DETAILAGENCY1 value) {
        this.detailagency1 = value;
    }

    /**
     * Gets the value of the detailrate property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILRATE }
     *     
     */
    public DETAILRATE getDETAILRATE() {
        return detailrate;
    }

    /**
     * Sets the value of the detailrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILRATE }
     *     
     */
    public void setDETAILRATE(DETAILRATE value) {
        this.detailrate = value;
    }

    /**
     * Gets the value of the detailratebasis property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILRATEBASIS }
     *     
     */
    public DETAILRATEBASIS getDETAILRATEBASIS() {
        return detailratebasis;
    }

    /**
     * Sets the value of the detailratebasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILRATEBASIS }
     *     
     */
    public void setDETAILRATEBASIS(DETAILRATEBASIS value) {
        this.detailratebasis = value;
    }

    /**
     * Gets the value of the detailcodelist2 property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILCODELIST2 }
     *     
     */
    public DETAILCODELIST2 getDETAILCODELIST2() {
        return detailcodelist2;
    }

    /**
     * Sets the value of the detailcodelist2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILCODELIST2 }
     *     
     */
    public void setDETAILCODELIST2(DETAILCODELIST2 value) {
        this.detailcodelist2 = value;
    }

    /**
     * Gets the value of the detailagency2 property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILAGENCY2 }
     *     
     */
    public DETAILAGENCY2 getDETAILAGENCY2() {
        return detailagency2;
    }

    /**
     * Sets the value of the detailagency2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILAGENCY2 }
     *     
     */
    public void setDETAILAGENCY2(DETAILAGENCY2 value) {
        this.detailagency2 = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link CATEGORY }
     *     
     */
    public CATEGORY getCATEGORY() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link CATEGORY }
     *     
     */
    public void setCATEGORY(CATEGORY value) {
        this.category = value;
    }

    /**
     * Gets the value of the partytaxid property.
     * 
     * @return
     *     possible object is
     *     {@link PARTYTAXID }
     *     
     */
    public PARTYTAXID getPARTYTAXID() {
        return partytaxid;
    }

    /**
     * Sets the value of the partytaxid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTYTAXID }
     *     
     */
    public void setPARTYTAXID(PARTYTAXID value) {
        this.partytaxid = value;
    }

    /**
     * Gets the value of the calculationsequence property.
     * 
     * @return
     *     possible object is
     *     {@link CALCULATIONSEQUENCE }
     *     
     */
    public CALCULATIONSEQUENCE getCALCULATIONSEQUENCE() {
        return calculationsequence;
    }

    /**
     * Sets the value of the calculationsequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CALCULATIONSEQUENCE }
     *     
     */
    public void setCALCULATIONSEQUENCE(CALCULATIONSEQUENCE value) {
        this.calculationsequence = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
