//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PLACE_QUALIFIER" minOccurs="0"/&gt;
 *         &lt;element ref="{}PLACE_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}PLACE"/&gt;
 *         &lt;element ref="{}RELATED_PLACE_COMPANY_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}RELATED_PLACE_AREA_1" minOccurs="0"/&gt;
 *         &lt;element ref="{}RELATED_PLACE_COMPANY_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_QUALIFIER_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}CODE_LIST_RESPONSIBLE_AGENCY_3" minOccurs="0"/&gt;
 *         &lt;element ref="{}RELATED_PLACE_AREA_2" minOccurs="0"/&gt;
 *         &lt;element ref="{}RELATION_CODE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "placequalifier",
    "placeid",
    "codelistqualifier1",
    "codelistresponsibleagency1",
    "place",
    "relatedplacecompany1",
    "codelistqualifier2",
    "codelistresponsibleagency2",
    "relatedplacearea1",
    "relatedplacecompany2",
    "codelistqualifier3",
    "codelistresponsibleagency3",
    "relatedplacearea2",
    "relationcode"
})
@XmlRootElement(name = "E1VDEWLOC_3")
public class E1VDEWLOC3 {

    @XmlElement(name = "PLACE_QUALIFIER")
    protected PLACEQUALIFIER placequalifier;
    @XmlElement(name = "PLACE_ID")
    protected PLACEID placeid;
    @XmlElement(name = "CODE_LIST_QUALIFIER_1")
    protected CODELISTQUALIFIER1 codelistqualifier1;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_1")
    protected CODELISTRESPONSIBLEAGENCY1 codelistresponsibleagency1;
    @XmlElement(name = "PLACE", required = true)
    protected PLACE place;
    @XmlElement(name = "RELATED_PLACE_COMPANY_1")
    protected RELATEDPLACECOMPANY1 relatedplacecompany1;
    @XmlElement(name = "CODE_LIST_QUALIFIER_2")
    protected CODELISTQUALIFIER2 codelistqualifier2;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_2")
    protected CODELISTRESPONSIBLEAGENCY2 codelistresponsibleagency2;
    @XmlElement(name = "RELATED_PLACE_AREA_1")
    protected RELATEDPLACEAREA1 relatedplacearea1;
    @XmlElement(name = "RELATED_PLACE_COMPANY_2")
    protected RELATEDPLACECOMPANY2 relatedplacecompany2;
    @XmlElement(name = "CODE_LIST_QUALIFIER_3")
    protected CODELISTQUALIFIER3 codelistqualifier3;
    @XmlElement(name = "CODE_LIST_RESPONSIBLE_AGENCY_3")
    protected CODELISTRESPONSIBLEAGENCY3 codelistresponsibleagency3;
    @XmlElement(name = "RELATED_PLACE_AREA_2")
    protected RELATEDPLACEAREA2 relatedplacearea2;
    @XmlElement(name = "RELATION_CODE")
    protected RELATIONCODE relationcode;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the placequalifier property.
     * 
     * @return
     *     possible object is
     *     {@link PLACEQUALIFIER }
     *     
     */
    public PLACEQUALIFIER getPLACEQUALIFIER() {
        return placequalifier;
    }

    /**
     * Sets the value of the placequalifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PLACEQUALIFIER }
     *     
     */
    public void setPLACEQUALIFIER(PLACEQUALIFIER value) {
        this.placequalifier = value;
    }

    /**
     * Gets the value of the placeid property.
     * 
     * @return
     *     possible object is
     *     {@link PLACEID }
     *     
     */
    public PLACEID getPLACEID() {
        return placeid;
    }

    /**
     * Sets the value of the placeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PLACEID }
     *     
     */
    public void setPLACEID(PLACEID value) {
        this.placeid = value;
    }

    /**
     * Gets the value of the codelistqualifier1 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER1 }
     *     
     */
    public CODELISTQUALIFIER1 getCODELISTQUALIFIER1() {
        return codelistqualifier1;
    }

    /**
     * Sets the value of the codelistqualifier1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER1 }
     *     
     */
    public void setCODELISTQUALIFIER1(CODELISTQUALIFIER1 value) {
        this.codelistqualifier1 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency1 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY1 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY1 getCODELISTRESPONSIBLEAGENCY1() {
        return codelistresponsibleagency1;
    }

    /**
     * Sets the value of the codelistresponsibleagency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY1 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY1(CODELISTRESPONSIBLEAGENCY1 value) {
        this.codelistresponsibleagency1 = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link PLACE }
     *     
     */
    public PLACE getPLACE() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link PLACE }
     *     
     */
    public void setPLACE(PLACE value) {
        this.place = value;
    }

    /**
     * Gets the value of the relatedplacecompany1 property.
     * 
     * @return
     *     possible object is
     *     {@link RELATEDPLACECOMPANY1 }
     *     
     */
    public RELATEDPLACECOMPANY1 getRELATEDPLACECOMPANY1() {
        return relatedplacecompany1;
    }

    /**
     * Sets the value of the relatedplacecompany1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATEDPLACECOMPANY1 }
     *     
     */
    public void setRELATEDPLACECOMPANY1(RELATEDPLACECOMPANY1 value) {
        this.relatedplacecompany1 = value;
    }

    /**
     * Gets the value of the codelistqualifier2 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER2 }
     *     
     */
    public CODELISTQUALIFIER2 getCODELISTQUALIFIER2() {
        return codelistqualifier2;
    }

    /**
     * Sets the value of the codelistqualifier2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER2 }
     *     
     */
    public void setCODELISTQUALIFIER2(CODELISTQUALIFIER2 value) {
        this.codelistqualifier2 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency2 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY2 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY2 getCODELISTRESPONSIBLEAGENCY2() {
        return codelistresponsibleagency2;
    }

    /**
     * Sets the value of the codelistresponsibleagency2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY2 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY2(CODELISTRESPONSIBLEAGENCY2 value) {
        this.codelistresponsibleagency2 = value;
    }

    /**
     * Gets the value of the relatedplacearea1 property.
     * 
     * @return
     *     possible object is
     *     {@link RELATEDPLACEAREA1 }
     *     
     */
    public RELATEDPLACEAREA1 getRELATEDPLACEAREA1() {
        return relatedplacearea1;
    }

    /**
     * Sets the value of the relatedplacearea1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATEDPLACEAREA1 }
     *     
     */
    public void setRELATEDPLACEAREA1(RELATEDPLACEAREA1 value) {
        this.relatedplacearea1 = value;
    }

    /**
     * Gets the value of the relatedplacecompany2 property.
     * 
     * @return
     *     possible object is
     *     {@link RELATEDPLACECOMPANY2 }
     *     
     */
    public RELATEDPLACECOMPANY2 getRELATEDPLACECOMPANY2() {
        return relatedplacecompany2;
    }

    /**
     * Sets the value of the relatedplacecompany2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATEDPLACECOMPANY2 }
     *     
     */
    public void setRELATEDPLACECOMPANY2(RELATEDPLACECOMPANY2 value) {
        this.relatedplacecompany2 = value;
    }

    /**
     * Gets the value of the codelistqualifier3 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTQUALIFIER3 }
     *     
     */
    public CODELISTQUALIFIER3 getCODELISTQUALIFIER3() {
        return codelistqualifier3;
    }

    /**
     * Sets the value of the codelistqualifier3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTQUALIFIER3 }
     *     
     */
    public void setCODELISTQUALIFIER3(CODELISTQUALIFIER3 value) {
        this.codelistqualifier3 = value;
    }

    /**
     * Gets the value of the codelistresponsibleagency3 property.
     * 
     * @return
     *     possible object is
     *     {@link CODELISTRESPONSIBLEAGENCY3 }
     *     
     */
    public CODELISTRESPONSIBLEAGENCY3 getCODELISTRESPONSIBLEAGENCY3() {
        return codelistresponsibleagency3;
    }

    /**
     * Sets the value of the codelistresponsibleagency3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODELISTRESPONSIBLEAGENCY3 }
     *     
     */
    public void setCODELISTRESPONSIBLEAGENCY3(CODELISTRESPONSIBLEAGENCY3 value) {
        this.codelistresponsibleagency3 = value;
    }

    /**
     * Gets the value of the relatedplacearea2 property.
     * 
     * @return
     *     possible object is
     *     {@link RELATEDPLACEAREA2 }
     *     
     */
    public RELATEDPLACEAREA2 getRELATEDPLACEAREA2() {
        return relatedplacearea2;
    }

    /**
     * Sets the value of the relatedplacearea2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATEDPLACEAREA2 }
     *     
     */
    public void setRELATEDPLACEAREA2(RELATEDPLACEAREA2 value) {
        this.relatedplacearea2 = value;
    }

    /**
     * Gets the value of the relationcode property.
     * 
     * @return
     *     possible object is
     *     {@link RELATIONCODE }
     *     
     */
    public RELATIONCODE getRELATIONCODE() {
        return relationcode;
    }

    /**
     * Sets the value of the relationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATIONCODE }
     *     
     */
    public void setRELATIONCODE(RELATIONCODE value) {
        this.relationcode = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
