//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}AGREE_TYPE_ID" minOccurs="0"/&gt;
 *         &lt;element ref="{}AGREE_TYPE_DESCRIPTION" minOccurs="0"/&gt;
 *         &lt;element ref="{}AGREE_TYPE_CODE_LIST" minOccurs="0"/&gt;
 *         &lt;element ref="{}AGREE_TYPE_AGENCY" minOccurs="0"/&gt;
 *         &lt;element ref="{}AGREE_TYPE" minOccurs="0"/&gt;
 *         &lt;element ref="{}SERVICE_LAYER" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agreetypeid",
    "agreetypedescription",
    "agreetypecodelist",
    "agreetypeagency",
    "agreetype",
    "servicelayer"
})
@XmlRootElement(name = "E1VDEWAGR")
public class E1VDEWAGR {

    @XmlElement(name = "AGREE_TYPE_ID")
    protected AGREETYPEID agreetypeid;
    @XmlElement(name = "AGREE_TYPE_DESCRIPTION")
    protected AGREETYPEDESCRIPTION agreetypedescription;
    @XmlElement(name = "AGREE_TYPE_CODE_LIST")
    protected AGREETYPECODELIST agreetypecodelist;
    @XmlElement(name = "AGREE_TYPE_AGENCY")
    protected AGREETYPEAGENCY agreetypeagency;
    @XmlElement(name = "AGREE_TYPE")
    protected AGREETYPE agreetype;
    @XmlElement(name = "SERVICE_LAYER")
    protected SERVICELAYER servicelayer;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the agreetypeid property.
     * 
     * @return
     *     possible object is
     *     {@link AGREETYPEID }
     *     
     */
    public AGREETYPEID getAGREETYPEID() {
        return agreetypeid;
    }

    /**
     * Sets the value of the agreetypeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGREETYPEID }
     *     
     */
    public void setAGREETYPEID(AGREETYPEID value) {
        this.agreetypeid = value;
    }

    /**
     * Gets the value of the agreetypedescription property.
     * 
     * @return
     *     possible object is
     *     {@link AGREETYPEDESCRIPTION }
     *     
     */
    public AGREETYPEDESCRIPTION getAGREETYPEDESCRIPTION() {
        return agreetypedescription;
    }

    /**
     * Sets the value of the agreetypedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGREETYPEDESCRIPTION }
     *     
     */
    public void setAGREETYPEDESCRIPTION(AGREETYPEDESCRIPTION value) {
        this.agreetypedescription = value;
    }

    /**
     * Gets the value of the agreetypecodelist property.
     * 
     * @return
     *     possible object is
     *     {@link AGREETYPECODELIST }
     *     
     */
    public AGREETYPECODELIST getAGREETYPECODELIST() {
        return agreetypecodelist;
    }

    /**
     * Sets the value of the agreetypecodelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGREETYPECODELIST }
     *     
     */
    public void setAGREETYPECODELIST(AGREETYPECODELIST value) {
        this.agreetypecodelist = value;
    }

    /**
     * Gets the value of the agreetypeagency property.
     * 
     * @return
     *     possible object is
     *     {@link AGREETYPEAGENCY }
     *     
     */
    public AGREETYPEAGENCY getAGREETYPEAGENCY() {
        return agreetypeagency;
    }

    /**
     * Sets the value of the agreetypeagency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGREETYPEAGENCY }
     *     
     */
    public void setAGREETYPEAGENCY(AGREETYPEAGENCY value) {
        this.agreetypeagency = value;
    }

    /**
     * Gets the value of the agreetype property.
     * 
     * @return
     *     possible object is
     *     {@link AGREETYPE }
     *     
     */
    public AGREETYPE getAGREETYPE() {
        return agreetype;
    }

    /**
     * Sets the value of the agreetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGREETYPE }
     *     
     */
    public void setAGREETYPE(AGREETYPE value) {
        this.agreetype = value;
    }

    /**
     * Gets the value of the servicelayer property.
     * 
     * @return
     *     possible object is
     *     {@link SERVICELAYER }
     *     
     */
    public SERVICELAYER getSERVICELAYER() {
        return servicelayer;
    }

    /**
     * Sets the value of the servicelayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SERVICELAYER }
     *     
     */
    public void setSERVICELAYER(SERVICELAYER value) {
        this.servicelayer = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
