//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}COMMNUMBER" minOccurs="0"/&gt;
 *         &lt;element ref="{}COMMQUALF" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="SEGMENT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commnumber",
    "commqualf"
})
@XmlRootElement(name = "E1VDEWCOM_2")
public class E1VDEWCOM2 {

    @XmlElement(name = "COMMNUMBER")
    protected COMMNUMBER commnumber;
    @XmlElement(name = "COMMQUALF")
    protected COMMQUALF commqualf;
    @XmlAttribute(name = "SEGMENT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String segment;

    /**
     * Gets the value of the commnumber property.
     * 
     * @return
     *     possible object is
     *     {@link COMMNUMBER }
     *     
     */
    public COMMNUMBER getCOMMNUMBER() {
        return commnumber;
    }

    /**
     * Sets the value of the commnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMMNUMBER }
     *     
     */
    public void setCOMMNUMBER(COMMNUMBER value) {
        this.commnumber = value;
    }

    /**
     * Gets the value of the commqualf property.
     * 
     * @return
     *     possible object is
     *     {@link COMMQUALF }
     *     
     */
    public COMMQUALF getCOMMQUALF() {
        return commqualf;
    }

    /**
     * Sets the value of the commqualf property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMMQUALF }
     *     
     */
    public void setCOMMQUALF(COMMQUALF value) {
        this.commqualf = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
