//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.06 at 02:51:29 PM CEST 
//


package com.example.jaxbtest.entity.xml.pojo.utilmd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.jaxbtest.entity.xml.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.jaxbtest.entity.xml.generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACCESSREF }
     * 
     */
    public ACCESSREF createACCESSREF() {
        return new ACCESSREF();
    }

    /**
     * Create an instance of {@link ACCOUNTAGENCY }
     * 
     */
    public ACCOUNTAGENCY createACCOUNTAGENCY() {
        return new ACCOUNTAGENCY();
    }

    /**
     * Create an instance of {@link ACCOUNTCODELIST }
     * 
     */
    public ACCOUNTCODELIST createACCOUNTCODELIST() {
        return new ACCOUNTCODELIST();
    }

    /**
     * Create an instance of {@link ACCOUNTCURRENCY }
     * 
     */
    public ACCOUNTCURRENCY createACCOUNTCURRENCY() {
        return new ACCOUNTCURRENCY();
    }

    /**
     * Create an instance of {@link ACCOUNTHOLDER1 }
     * 
     */
    public ACCOUNTHOLDER1 createACCOUNTHOLDER1() {
        return new ACCOUNTHOLDER1();
    }

    /**
     * Create an instance of {@link ACCOUNTHOLDER2 }
     * 
     */
    public ACCOUNTHOLDER2 createACCOUNTHOLDER2() {
        return new ACCOUNTHOLDER2();
    }

    /**
     * Create an instance of {@link ACCOUNTID }
     * 
     */
    public ACCOUNTID createACCOUNTID() {
        return new ACCOUNTID();
    }

    /**
     * Create an instance of {@link ACCOUNTNUMBER }
     * 
     */
    public ACCOUNTNUMBER createACCOUNTNUMBER() {
        return new ACCOUNTNUMBER();
    }

    /**
     * Create an instance of {@link ACTION }
     * 
     */
    public ACTION createACTION() {
        return new ACTION();
    }

    /**
     * Create an instance of {@link ACTIONREQUEST }
     * 
     */
    public ACTIONREQUEST createACTIONREQUEST() {
        return new ACTIONREQUEST();
    }

    /**
     * Create an instance of {@link ACTIONREQUESTINFORM }
     * 
     */
    public ACTIONREQUESTINFORM createACTIONREQUESTINFORM() {
        return new ACTIONREQUESTINFORM();
    }

    /**
     * Create an instance of {@link AGENCY }
     * 
     */
    public AGENCY createAGENCY() {
        return new AGENCY();
    }

    /**
     * Create an instance of {@link AGREETYPE }
     * 
     */
    public AGREETYPE createAGREETYPE() {
        return new AGREETYPE();
    }

    /**
     * Create an instance of {@link AGREETYPEAGENCY }
     * 
     */
    public AGREETYPEAGENCY createAGREETYPEAGENCY() {
        return new AGREETYPEAGENCY();
    }

    /**
     * Create an instance of {@link AGREETYPECODELIST }
     * 
     */
    public AGREETYPECODELIST createAGREETYPECODELIST() {
        return new AGREETYPECODELIST();
    }

    /**
     * Create an instance of {@link AGREETYPEDESCRIPTION }
     * 
     */
    public AGREETYPEDESCRIPTION createAGREETYPEDESCRIPTION() {
        return new AGREETYPEDESCRIPTION();
    }

    /**
     * Create an instance of {@link AGREETYPEID }
     * 
     */
    public AGREETYPEID createAGREETYPEID() {
        return new AGREETYPEID();
    }

    /**
     * Create an instance of {@link ARCKEY }
     * 
     */
    public ARCKEY createARCKEY() {
        return new ARCKEY();
    }

    /**
     * Create an instance of {@link ASSESSMENTBASIS }
     * 
     */
    public ASSESSMENTBASIS createASSESSMENTBASIS() {
        return new ASSESSMENTBASIS();
    }

    /**
     * Create an instance of {@link ASSOCCODE }
     * 
     */
    public ASSOCCODE createASSOCCODE() {
        return new ASSOCCODE();
    }

    /**
     * Create an instance of {@link BANKBRANCH }
     * 
     */
    public BANKBRANCH createBANKBRANCH() {
        return new BANKBRANCH();
    }

    /**
     * Create an instance of {@link BANKBRANCHPLACE }
     * 
     */
    public BANKBRANCHPLACE createBANKBRANCHPLACE() {
        return new BANKBRANCHPLACE();
    }

    /**
     * Create an instance of {@link BANKCODELIST1 }
     * 
     */
    public BANKCODELIST1 createBANKCODELIST1() {
        return new BANKCODELIST1();
    }

    /**
     * Create an instance of {@link BANKCODELIST2 }
     * 
     */
    public BANKCODELIST2 createBANKCODELIST2() {
        return new BANKCODELIST2();
    }

    /**
     * Create an instance of {@link BANKID }
     * 
     */
    public BANKID createBANKID() {
        return new BANKID();
    }

    /**
     * Create an instance of {@link BANKNAME }
     * 
     */
    public BANKNAME createBANKNAME() {
        return new BANKNAME();
    }

    /**
     * Create an instance of {@link BANKRESPAGENCY1 }
     * 
     */
    public BANKRESPAGENCY1 createBANKRESPAGENCY1() {
        return new BANKRESPAGENCY1();
    }

    /**
     * Create an instance of {@link BANKRESPAGENCY2 }
     * 
     */
    public BANKRESPAGENCY2 createBANKRESPAGENCY2() {
        return new BANKRESPAGENCY2();
    }

    /**
     * Create an instance of {@link CALCULATIONSEQUENCE }
     * 
     */
    public CALCULATIONSEQUENCE createCALCULATIONSEQUENCE() {
        return new CALCULATIONSEQUENCE();
    }

    /**
     * Create an instance of {@link CATEGORY }
     * 
     */
    public CATEGORY createCATEGORY() {
        return new CATEGORY();
    }

    /**
     * Create an instance of {@link CATEGORYAGENCY }
     * 
     */
    public CATEGORYAGENCY createCATEGORYAGENCY() {
        return new CATEGORYAGENCY();
    }

    /**
     * Create an instance of {@link CATEGORYCODELISTID }
     * 
     */
    public CATEGORYCODELISTID createCATEGORYCODELISTID() {
        return new CATEGORYCODELISTID();
    }

    /**
     * Create an instance of {@link CHARACTERISTIC1 }
     * 
     */
    public CHARACTERISTIC1 createCHARACTERISTIC1() {
        return new CHARACTERISTIC1();
    }

    /**
     * Create an instance of {@link CHARACTERISTIC2 }
     * 
     */
    public CHARACTERISTIC2 createCHARACTERISTIC2() {
        return new CHARACTERISTIC2();
    }

    /**
     * Create an instance of {@link CHARACTERISTICID }
     * 
     */
    public CHARACTERISTICID createCHARACTERISTICID() {
        return new CHARACTERISTICID();
    }

    /**
     * Create an instance of {@link CHARACTERISTICVALUE1 }
     * 
     */
    public CHARACTERISTICVALUE1 createCHARACTERISTICVALUE1() {
        return new CHARACTERISTICVALUE1();
    }

    /**
     * Create an instance of {@link CHARACTERISTICVALUE2 }
     * 
     */
    public CHARACTERISTICVALUE2 createCHARACTERISTICVALUE2() {
        return new CHARACTERISTICVALUE2();
    }

    /**
     * Create an instance of {@link CHARACTERISTICVALUECODED }
     * 
     */
    public CHARACTERISTICVALUECODED createCHARACTERISTICVALUECODED() {
        return new CHARACTERISTICVALUECODED();
    }

    /**
     * Create an instance of {@link CIMTYP }
     * 
     */
    public CIMTYP createCIMTYP() {
        return new CIMTYP();
    }

    /**
     * Create an instance of {@link CITY }
     * 
     */
    public CITY createCITY() {
        return new CITY();
    }

    /**
     * Create an instance of {@link CODELISTID }
     * 
     */
    public CODELISTID createCODELISTID() {
        return new CODELISTID();
    }

    /**
     * Create an instance of {@link CODELISTQUALIFIER }
     * 
     */
    public CODELISTQUALIFIER createCODELISTQUALIFIER() {
        return new CODELISTQUALIFIER();
    }

    /**
     * Create an instance of {@link CODELISTQUALIFIER1 }
     * 
     */
    public CODELISTQUALIFIER1 createCODELISTQUALIFIER1() {
        return new CODELISTQUALIFIER1();
    }

    /**
     * Create an instance of {@link CODELISTQUALIFIER2 }
     * 
     */
    public CODELISTQUALIFIER2 createCODELISTQUALIFIER2() {
        return new CODELISTQUALIFIER2();
    }

    /**
     * Create an instance of {@link CODELISTQUALIFIER3 }
     * 
     */
    public CODELISTQUALIFIER3 createCODELISTQUALIFIER3() {
        return new CODELISTQUALIFIER3();
    }

    /**
     * Create an instance of {@link CODELISTQUALIFIER4 }
     * 
     */
    public CODELISTQUALIFIER4 createCODELISTQUALIFIER4() {
        return new CODELISTQUALIFIER4();
    }

    /**
     * Create an instance of {@link CODELISTQUALIFIER5 }
     * 
     */
    public CODELISTQUALIFIER5 createCODELISTQUALIFIER5() {
        return new CODELISTQUALIFIER5();
    }

    /**
     * Create an instance of {@link CODELISTRESPONSIBLEAGENCY }
     * 
     */
    public CODELISTRESPONSIBLEAGENCY createCODELISTRESPONSIBLEAGENCY() {
        return new CODELISTRESPONSIBLEAGENCY();
    }

    /**
     * Create an instance of {@link CODELISTRESPONSIBLEAGENCY1 }
     * 
     */
    public CODELISTRESPONSIBLEAGENCY1 createCODELISTRESPONSIBLEAGENCY1() {
        return new CODELISTRESPONSIBLEAGENCY1();
    }

    /**
     * Create an instance of {@link CODELISTRESPONSIBLEAGENCY2 }
     * 
     */
    public CODELISTRESPONSIBLEAGENCY2 createCODELISTRESPONSIBLEAGENCY2() {
        return new CODELISTRESPONSIBLEAGENCY2();
    }

    /**
     * Create an instance of {@link CODELISTRESPONSIBLEAGENCY3 }
     * 
     */
    public CODELISTRESPONSIBLEAGENCY3 createCODELISTRESPONSIBLEAGENCY3() {
        return new CODELISTRESPONSIBLEAGENCY3();
    }

    /**
     * Create an instance of {@link CODELISTRESPONSIBLEAGENCY4 }
     * 
     */
    public CODELISTRESPONSIBLEAGENCY4 createCODELISTRESPONSIBLEAGENCY4() {
        return new CODELISTRESPONSIBLEAGENCY4();
    }

    /**
     * Create an instance of {@link CODELISTRESPONSIBLEAGENCY5 }
     * 
     */
    public CODELISTRESPONSIBLEAGENCY5 createCODELISTRESPONSIBLEAGENCY5() {
        return new CODELISTRESPONSIBLEAGENCY5();
    }

    /**
     * Create an instance of {@link CODELIST }
     * 
     */
    public CODELIST createCODELIST() {
        return new CODELIST();
    }

    /**
     * Create an instance of {@link CODELISTAGENCY }
     * 
     */
    public CODELISTAGENCY createCODELISTAGENCY() {
        return new CODELISTAGENCY();
    }

    /**
     * Create an instance of {@link COMMNUMBER }
     * 
     */
    public COMMNUMBER createCOMMNUMBER() {
        return new COMMNUMBER();
    }

    /**
     * Create an instance of {@link COMMQUALF }
     * 
     */
    public COMMQUALF createCOMMQUALF() {
        return new COMMQUALF();
    }

    /**
     * Create an instance of {@link CONFLEVEL }
     * 
     */
    public CONFLEVEL createCONFLEVEL() {
        return new CONFLEVEL();
    }

    /**
     * Create an instance of {@link CONTACTFUNC }
     * 
     */
    public CONTACTFUNC createCONTACTFUNC() {
        return new CONTACTFUNC();
    }

    /**
     * Create an instance of {@link CONTACTID }
     * 
     */
    public CONTACTID createCONTACTID() {
        return new CONTACTID();
    }

    /**
     * Create an instance of {@link CONTACTNAME }
     * 
     */
    public CONTACTNAME createCONTACTNAME() {
        return new CONTACTNAME();
    }

    /**
     * Create an instance of {@link CONTROLAGENCY }
     * 
     */
    public CONTROLAGENCY createCONTROLAGENCY() {
        return new CONTROLAGENCY();
    }

    /**
     * Create an instance of {@link COUNTRY }
     * 
     */
    public COUNTRY createCOUNTRY() {
        return new COUNTRY();
    }

    /**
     * Create an instance of {@link CREDAT }
     * 
     */
    public CREDAT createCREDAT() {
        return new CREDAT();
    }

    /**
     * Create an instance of {@link CRETIM }
     * 
     */
    public CRETIM createCRETIM() {
        return new CRETIM();
    }

    /**
     * Create an instance of {@link CURRENCYID }
     * 
     */
    public CURRENCYID createCURRENCYID() {
        return new CURRENCYID();
    }

    /**
     * Create an instance of {@link CURRENCYQUALIFIER }
     * 
     */
    public CURRENCYQUALIFIER createCURRENCYQUALIFIER() {
        return new CURRENCYQUALIFIER();
    }

    /**
     * Create an instance of {@link DATUM }
     * 
     */
    public DATUM createDATUM() {
        return new DATUM();
    }

    /**
     * Create an instance of {@link DATUMQUALIFIER }
     * 
     */
    public DATUMQUALIFIER createDATUMQUALIFIER() {
        return new DATUMQUALIFIER();
    }

    /**
     * Create an instance of {@link DETAILAGENCY1 }
     * 
     */
    public DETAILAGENCY1 createDETAILAGENCY1() {
        return new DETAILAGENCY1();
    }

    /**
     * Create an instance of {@link DETAILAGENCY2 }
     * 
     */
    public DETAILAGENCY2 createDETAILAGENCY2() {
        return new DETAILAGENCY2();
    }

    /**
     * Create an instance of {@link DETAILCODELIST1 }
     * 
     */
    public DETAILCODELIST1 createDETAILCODELIST1() {
        return new DETAILCODELIST1();
    }

    /**
     * Create an instance of {@link DETAILCODELIST2 }
     * 
     */
    public DETAILCODELIST2 createDETAILCODELIST2() {
        return new DETAILCODELIST2();
    }

    /**
     * Create an instance of {@link DETAILRATE }
     * 
     */
    public DETAILRATE createDETAILRATE() {
        return new DETAILRATE();
    }

    /**
     * Create an instance of {@link DETAILRATEBASIS }
     * 
     */
    public DETAILRATEBASIS createDETAILRATEBASIS() {
        return new DETAILRATEBASIS();
    }

    /**
     * Create an instance of {@link DETAILRATEID }
     * 
     */
    public DETAILRATEID createDETAILRATEID() {
        return new DETAILRATEID();
    }

    /**
     * Create an instance of {@link DIRECT }
     * 
     */
    public DIRECT createDIRECT() {
        return new DIRECT();
    }

    /**
     * Create an instance of {@link DOCNUM }
     * 
     */
    public DOCNUM createDOCNUM() {
        return new DOCNUM();
    }

    /**
     * Create an instance of {@link DOCREL }
     * 
     */
    public DOCREL createDOCREL() {
        return new DOCREL();
    }

    /**
     * Create an instance of {@link DOCUMENTFUNC }
     * 
     */
    public DOCUMENTFUNC createDOCUMENTFUNC() {
        return new DOCUMENTFUNC();
    }

    /**
     * Create an instance of {@link DOCUMENTNUMBER }
     * 
     */
    public DOCUMENTNUMBER createDOCUMENTNUMBER() {
        return new DOCUMENTNUMBER();
    }

    /**
     * Create an instance of {@link DTFFUNCTION }
     * 
     */
    public DTFFUNCTION createDTFFUNCTION() {
        return new DTFFUNCTION();
    }

    /**
     * Create an instance of {@link E1VDEWAGR }
     * 
     */
    public E1VDEWAGR createE1VDEWAGR() {
        return new E1VDEWAGR();
    }

    /**
     * Create an instance of {@link SERVICELAYER }
     * 
     */
    public SERVICELAYER createSERVICELAYER() {
        return new SERVICELAYER();
    }

    /**
     * Create an instance of {@link E1VDEWBGM1 }
     * 
     */
    public E1VDEWBGM1 createE1VDEWBGM1() {
        return new E1VDEWBGM1();
    }

    /**
     * Create an instance of {@link NAME }
     * 
     */
    public NAME createNAME() {
        return new NAME();
    }

    /**
     * Create an instance of {@link FULLNAME }
     * 
     */
    public FULLNAME createFULLNAME() {
        return new FULLNAME();
    }

    /**
     * Create an instance of {@link VERSION }
     * 
     */
    public VERSION createVERSION() {
        return new VERSION();
    }

    /**
     * Create an instance of {@link REVISION }
     * 
     */
    public REVISION createREVISION() {
        return new REVISION();
    }

    /**
     * Create an instance of {@link RESPONSETYPE }
     * 
     */
    public RESPONSETYPE createRESPONSETYPE() {
        return new RESPONSETYPE();
    }

    /**
     * Create an instance of {@link E1VDEWCAV3 }
     * 
     */
    public E1VDEWCAV3 createE1VDEWCAV3() {
        return new E1VDEWCAV3();
    }

    /**
     * Create an instance of {@link E1VDEWCAV4 }
     * 
     */
    public E1VDEWCAV4 createE1VDEWCAV4() {
        return new E1VDEWCAV4();
    }

    /**
     * Create an instance of {@link E1VDEWCCI3 }
     * 
     */
    public E1VDEWCCI3 createE1VDEWCCI3() {
        return new E1VDEWCCI3();
    }

    /**
     * Create an instance of {@link PROPERTYCLASS }
     * 
     */
    public PROPERTYCLASS createPROPERTYCLASS() {
        return new PROPERTYCLASS();
    }

    /**
     * Create an instance of {@link PROPERTYMEASURE }
     * 
     */
    public PROPERTYMEASURE createPROPERTYMEASURE() {
        return new PROPERTYMEASURE();
    }

    /**
     * Create an instance of {@link MEASUREMENTSIGNIFICANCE }
     * 
     */
    public MEASUREMENTSIGNIFICANCE createMEASUREMENTSIGNIFICANCE() {
        return new MEASUREMENTSIGNIFICANCE();
    }

    /**
     * Create an instance of {@link MEASUREMENTATTRIBUTEID }
     * 
     */
    public MEASUREMENTATTRIBUTEID createMEASUREMENTATTRIBUTEID() {
        return new MEASUREMENTATTRIBUTEID();
    }

    /**
     * Create an instance of {@link MEASUREMENTATTRIBUTE }
     * 
     */
    public MEASUREMENTATTRIBUTE createMEASUREMENTATTRIBUTE() {
        return new MEASUREMENTATTRIBUTE();
    }

    /**
     * Create an instance of {@link E1VDEWCCI4 }
     * 
     */
    public E1VDEWCCI4 createE1VDEWCCI4() {
        return new E1VDEWCCI4();
    }

    /**
     * Create an instance of {@link E1VDEWCOM }
     * 
     */
    public E1VDEWCOM createE1VDEWCOM() {
        return new E1VDEWCOM();
    }

    /**
     * Create an instance of {@link E1VDEWCOM2 }
     * 
     */
    public E1VDEWCOM2 createE1VDEWCOM2() {
        return new E1VDEWCOM2();
    }

    /**
     * Create an instance of {@link E1VDEWCTA }
     * 
     */
    public E1VDEWCTA createE1VDEWCTA() {
        return new E1VDEWCTA();
    }

    /**
     * Create an instance of {@link E1VDEWCTA2 }
     * 
     */
    public E1VDEWCTA2 createE1VDEWCTA2() {
        return new E1VDEWCTA2();
    }

    /**
     * Create an instance of {@link E1VDEWDTM }
     * 
     */
    public E1VDEWDTM createE1VDEWDTM() {
        return new E1VDEWDTM();
    }

    /**
     * Create an instance of {@link FORMAT }
     * 
     */
    public FORMAT createFORMAT() {
        return new FORMAT();
    }

    /**
     * Create an instance of {@link E1VDEWDTM2 }
     * 
     */
    public E1VDEWDTM2 createE1VDEWDTM2() {
        return new E1VDEWDTM2();
    }

    /**
     * Create an instance of {@link E1VDEWDTM3 }
     * 
     */
    public E1VDEWDTM3 createE1VDEWDTM3() {
        return new E1VDEWDTM3();
    }

    /**
     * Create an instance of {@link E1VDEWDTM4 }
     * 
     */
    public E1VDEWDTM4 createE1VDEWDTM4() {
        return new E1VDEWDTM4();
    }

    /**
     * Create an instance of {@link E1VDEWDTM6 }
     * 
     */
    public E1VDEWDTM6 createE1VDEWDTM6() {
        return new E1VDEWDTM6();
    }

    /**
     * Create an instance of {@link E1VDEWFII3 }
     * 
     */
    public E1VDEWFII3 createE1VDEWFII3() {
        return new E1VDEWFII3();
    }

    /**
     * Create an instance of {@link PARTYID }
     * 
     */
    public PARTYID createPARTYID() {
        return new PARTYID();
    }

    /**
     * Create an instance of {@link E1VDEWFII4 }
     * 
     */
    public E1VDEWFII4 createE1VDEWFII4() {
        return new E1VDEWFII4();
    }

    /**
     * Create an instance of {@link E1VDEWFTX2 }
     * 
     */
    public E1VDEWFTX2 createE1VDEWFTX2() {
        return new E1VDEWFTX2();
    }

    /**
     * Create an instance of {@link TEXTSUBJECTQUALIFIER }
     * 
     */
    public TEXTSUBJECTQUALIFIER createTEXTSUBJECTQUALIFIER() {
        return new TEXTSUBJECTQUALIFIER();
    }

    /**
     * Create an instance of {@link TEXTFUNCTIONCODE }
     * 
     */
    public TEXTFUNCTIONCODE createTEXTFUNCTIONCODE() {
        return new TEXTFUNCTIONCODE();
    }

    /**
     * Create an instance of {@link FREETEXTCODE }
     * 
     */
    public FREETEXTCODE createFREETEXTCODE() {
        return new FREETEXTCODE();
    }

    /**
     * Create an instance of {@link FREETEXT1 }
     * 
     */
    public FREETEXT1 createFREETEXT1() {
        return new FREETEXT1();
    }

    /**
     * Create an instance of {@link FREETEXT2 }
     * 
     */
    public FREETEXT2 createFREETEXT2() {
        return new FREETEXT2();
    }

    /**
     * Create an instance of {@link FREETEXT3 }
     * 
     */
    public FREETEXT3 createFREETEXT3() {
        return new FREETEXT3();
    }

    /**
     * Create an instance of {@link FREETEXT4 }
     * 
     */
    public FREETEXT4 createFREETEXT4() {
        return new FREETEXT4();
    }

    /**
     * Create an instance of {@link FREETEXT5 }
     * 
     */
    public FREETEXT5 createFREETEXT5() {
        return new FREETEXT5();
    }

    /**
     * Create an instance of {@link LANGUAGE }
     * 
     */
    public LANGUAGE createLANGUAGE() {
        return new LANGUAGE();
    }

    /**
     * Create an instance of {@link TEXTFORMAT }
     * 
     */
    public TEXTFORMAT createTEXTFORMAT() {
        return new TEXTFORMAT();
    }

    /**
     * Create an instance of {@link E1VDEWIDE2 }
     * 
     */
    public E1VDEWIDE2 createE1VDEWIDE2() {
        return new E1VDEWIDE2();
    }

    /**
     * Create an instance of {@link OBJECTTYPE }
     * 
     */
    public OBJECTTYPE createOBJECTTYPE() {
        return new OBJECTTYPE();
    }

    /**
     * Create an instance of {@link IDNUMBER }
     * 
     */
    public IDNUMBER createIDNUMBER() {
        return new IDNUMBER();
    }

    /**
     * Create an instance of {@link IDCODE }
     * 
     */
    public IDCODE createIDCODE() {
        return new IDCODE();
    }

    /**
     * Create an instance of {@link IDSTATUS }
     * 
     */
    public IDSTATUS createIDSTATUS() {
        return new IDSTATUS();
    }

    /**
     * Create an instance of {@link PARTYIDCODE }
     * 
     */
    public PARTYIDCODE createPARTYIDCODE() {
        return new PARTYIDCODE();
    }

    /**
     * Create an instance of {@link PARTYAGENCY }
     * 
     */
    public PARTYAGENCY createPARTYAGENCY() {
        return new PARTYAGENCY();
    }

    /**
     * Create an instance of {@link STATUSDESCR }
     * 
     */
    public STATUSDESCR createSTATUSDESCR() {
        return new STATUSDESCR();
    }

    /**
     * Create an instance of {@link POSHIERARCHI }
     * 
     */
    public POSHIERARCHI createPOSHIERARCHI() {
        return new POSHIERARCHI();
    }

    /**
     * Create an instance of {@link POSSEQUENCENR }
     * 
     */
    public POSSEQUENCENR createPOSSEQUENCENR() {
        return new POSSEQUENCENR();
    }

    /**
     * Create an instance of {@link PRODUCTDESCR }
     * 
     */
    public PRODUCTDESCR createPRODUCTDESCR() {
        return new PRODUCTDESCR();
    }

    /**
     * Create an instance of {@link PRODUCTID }
     * 
     */
    public PRODUCTID createPRODUCTID() {
        return new PRODUCTID();
    }

    /**
     * Create an instance of {@link PRODUCTAGENCY }
     * 
     */
    public PRODUCTAGENCY createPRODUCTAGENCY() {
        return new PRODUCTAGENCY();
    }

    /**
     * Create an instance of {@link PRODUCTCHARACTERISTIC1 }
     * 
     */
    public PRODUCTCHARACTERISTIC1 createPRODUCTCHARACTERISTIC1() {
        return new PRODUCTCHARACTERISTIC1();
    }

    /**
     * Create an instance of {@link PRODUCTCHARACTERISTIC2 }
     * 
     */
    public PRODUCTCHARACTERISTIC2 createPRODUCTCHARACTERISTIC2() {
        return new PRODUCTCHARACTERISTIC2();
    }

    /**
     * Create an instance of {@link E1VDEWLOC3 }
     * 
     */
    public E1VDEWLOC3 createE1VDEWLOC3() {
        return new E1VDEWLOC3();
    }

    /**
     * Create an instance of {@link PLACEQUALIFIER }
     * 
     */
    public PLACEQUALIFIER createPLACEQUALIFIER() {
        return new PLACEQUALIFIER();
    }

    /**
     * Create an instance of {@link PLACEID }
     * 
     */
    public PLACEID createPLACEID() {
        return new PLACEID();
    }

    /**
     * Create an instance of {@link PLACE }
     * 
     */
    public PLACE createPLACE() {
        return new PLACE();
    }

    /**
     * Create an instance of {@link RELATEDPLACECOMPANY1 }
     * 
     */
    public RELATEDPLACECOMPANY1 createRELATEDPLACECOMPANY1() {
        return new RELATEDPLACECOMPANY1();
    }

    /**
     * Create an instance of {@link RELATEDPLACEAREA1 }
     * 
     */
    public RELATEDPLACEAREA1 createRELATEDPLACEAREA1() {
        return new RELATEDPLACEAREA1();
    }

    /**
     * Create an instance of {@link RELATEDPLACECOMPANY2 }
     * 
     */
    public RELATEDPLACECOMPANY2 createRELATEDPLACECOMPANY2() {
        return new RELATEDPLACECOMPANY2();
    }

    /**
     * Create an instance of {@link RELATEDPLACEAREA2 }
     * 
     */
    public RELATEDPLACEAREA2 createRELATEDPLACEAREA2() {
        return new RELATEDPLACEAREA2();
    }

    /**
     * Create an instance of {@link RELATIONCODE }
     * 
     */
    public RELATIONCODE createRELATIONCODE() {
        return new RELATIONCODE();
    }

    /**
     * Create an instance of {@link E1VDEWSTS2 }
     * 
     */
    public E1VDEWSTS2 createE1VDEWSTS2() {
        return new E1VDEWSTS2();
    }

    /**
     * Create an instance of {@link STATUSDESCRIPTIONCODE }
     * 
     */
    public STATUSDESCRIPTIONCODE createSTATUSDESCRIPTIONCODE() {
        return new STATUSDESCRIPTIONCODE();
    }

    /**
     * Create an instance of {@link STATUSCODELISTID }
     * 
     */
    public STATUSCODELISTID createSTATUSCODELISTID() {
        return new STATUSCODELISTID();
    }

    /**
     * Create an instance of {@link STATUSAGENCY }
     * 
     */
    public STATUSAGENCY createSTATUSAGENCY() {
        return new STATUSAGENCY();
    }

    /**
     * Create an instance of {@link STATUSDESCRIPTION }
     * 
     */
    public STATUSDESCRIPTION createSTATUSDESCRIPTION() {
        return new STATUSDESCRIPTION();
    }

    /**
     * Create an instance of {@link REASON1DESCRIPTIONCODE }
     * 
     */
    public REASON1DESCRIPTIONCODE createREASON1DESCRIPTIONCODE() {
        return new REASON1DESCRIPTIONCODE();
    }

    /**
     * Create an instance of {@link REASON1CODELISTID }
     * 
     */
    public REASON1CODELISTID createREASON1CODELISTID() {
        return new REASON1CODELISTID();
    }

    /**
     * Create an instance of {@link REASON1AGENCY }
     * 
     */
    public REASON1AGENCY createREASON1AGENCY() {
        return new REASON1AGENCY();
    }

    /**
     * Create an instance of {@link REASON1DESCRIPTION }
     * 
     */
    public REASON1DESCRIPTION createREASON1DESCRIPTION() {
        return new REASON1DESCRIPTION();
    }

    /**
     * Create an instance of {@link REASON2DESCRIPTIONCODE }
     * 
     */
    public REASON2DESCRIPTIONCODE createREASON2DESCRIPTIONCODE() {
        return new REASON2DESCRIPTIONCODE();
    }

    /**
     * Create an instance of {@link REASON2CODELISTID }
     * 
     */
    public REASON2CODELISTID createREASON2CODELISTID() {
        return new REASON2CODELISTID();
    }

    /**
     * Create an instance of {@link REASON2AGENCY }
     * 
     */
    public REASON2AGENCY createREASON2AGENCY() {
        return new REASON2AGENCY();
    }

    /**
     * Create an instance of {@link REASON2DESCRIPTION }
     * 
     */
    public REASON2DESCRIPTION createREASON2DESCRIPTION() {
        return new REASON2DESCRIPTION();
    }

    /**
     * Create an instance of {@link REASON3DESCRIPTIONCODE }
     * 
     */
    public REASON3DESCRIPTIONCODE createREASON3DESCRIPTIONCODE() {
        return new REASON3DESCRIPTIONCODE();
    }

    /**
     * Create an instance of {@link REASON3CODELISTID }
     * 
     */
    public REASON3CODELISTID createREASON3CODELISTID() {
        return new REASON3CODELISTID();
    }

    /**
     * Create an instance of {@link REASON3AGENCY }
     * 
     */
    public REASON3AGENCY createREASON3AGENCY() {
        return new REASON3AGENCY();
    }

    /**
     * Create an instance of {@link REASON3DESCRIPTION }
     * 
     */
    public REASON3DESCRIPTION createREASON3DESCRIPTION() {
        return new REASON3DESCRIPTION();
    }

    /**
     * Create an instance of {@link REASON4DESCRIPTIONCODE }
     * 
     */
    public REASON4DESCRIPTIONCODE createREASON4DESCRIPTIONCODE() {
        return new REASON4DESCRIPTIONCODE();
    }

    /**
     * Create an instance of {@link REASON4CODELISTID }
     * 
     */
    public REASON4CODELISTID createREASON4CODELISTID() {
        return new REASON4CODELISTID();
    }

    /**
     * Create an instance of {@link REASON4AGENCY }
     * 
     */
    public REASON4AGENCY createREASON4AGENCY() {
        return new REASON4AGENCY();
    }

    /**
     * Create an instance of {@link REASON4DESCRIPTION }
     * 
     */
    public REASON4DESCRIPTION createREASON4DESCRIPTION() {
        return new REASON4DESCRIPTION();
    }

    /**
     * Create an instance of {@link REASON5DESCRIPTIONCODE }
     * 
     */
    public REASON5DESCRIPTIONCODE createREASON5DESCRIPTIONCODE() {
        return new REASON5DESCRIPTIONCODE();
    }

    /**
     * Create an instance of {@link REASON5CODELISTID }
     * 
     */
    public REASON5CODELISTID createREASON5CODELISTID() {
        return new REASON5CODELISTID();
    }

    /**
     * Create an instance of {@link REASON5AGENCY }
     * 
     */
    public REASON5AGENCY createREASON5AGENCY() {
        return new REASON5AGENCY();
    }

    /**
     * Create an instance of {@link REASON5DESCRIPTION }
     * 
     */
    public REASON5DESCRIPTION createREASON5DESCRIPTION() {
        return new REASON5DESCRIPTION();
    }

    /**
     * Create an instance of {@link E1VDEWTAX3 }
     * 
     */
    public E1VDEWTAX3 createE1VDEWTAX3() {
        return new E1VDEWTAX3();
    }

    /**
     * Create an instance of {@link TYPECODED }
     * 
     */
    public TYPECODED createTYPECODED() {
        return new TYPECODED();
    }

    /**
     * Create an instance of {@link TYPECODELIST }
     * 
     */
    public TYPECODELIST createTYPECODELIST() {
        return new TYPECODELIST();
    }

    /**
     * Create an instance of {@link TYPEAGENCY }
     * 
     */
    public TYPEAGENCY createTYPEAGENCY() {
        return new TYPEAGENCY();
    }

    /**
     * Create an instance of {@link TYPE }
     * 
     */
    public TYPE createTYPE() {
        return new TYPE();
    }

    /**
     * Create an instance of {@link PARTYTAXID }
     * 
     */
    public PARTYTAXID createPARTYTAXID() {
        return new PARTYTAXID();
    }

    /**
     * Create an instance of {@link E1VDEWINP }
     * 
     */
    public E1VDEWINP createE1VDEWINP() {
        return new E1VDEWINP();
    }

    /**
     * Create an instance of {@link INSTRUCPARTICIPANTSENDID }
     * 
     */
    public INSTRUCPARTICIPANTSENDID createINSTRUCPARTICIPANTSENDID() {
        return new INSTRUCPARTICIPANTSENDID();
    }

    /**
     * Create an instance of {@link INSTRUCPARTICIPANTRECEIVEID }
     * 
     */
    public INSTRUCPARTICIPANTRECEIVEID createINSTRUCPARTICIPANTRECEIVEID() {
        return new INSTRUCPARTICIPANTRECEIVEID();
    }

    /**
     * Create an instance of {@link INSTRUCTIONID }
     * 
     */
    public INSTRUCTIONID createINSTRUCTIONID() {
        return new INSTRUCTIONID();
    }

    /**
     * Create an instance of {@link INSTRUCTIONCODE }
     * 
     */
    public INSTRUCTIONCODE createINSTRUCTIONCODE() {
        return new INSTRUCTIONCODE();
    }

    /**
     * Create an instance of {@link INSTRUCTIONCODELIST }
     * 
     */
    public INSTRUCTIONCODELIST createINSTRUCTIONCODELIST() {
        return new INSTRUCTIONCODELIST();
    }

    /**
     * Create an instance of {@link INSTRUCTIONCODEAGENCY }
     * 
     */
    public INSTRUCTIONCODEAGENCY createINSTRUCTIONCODEAGENCY() {
        return new INSTRUCTIONCODEAGENCY();
    }

    /**
     * Create an instance of {@link INSTRUCTION }
     * 
     */
    public INSTRUCTION createINSTRUCTION() {
        return new INSTRUCTION();
    }

    /**
     * Create an instance of {@link INSTRUCTIONSTATUS }
     * 
     */
    public INSTRUCTIONSTATUS createINSTRUCTIONSTATUS() {
        return new INSTRUCTIONSTATUS();
    }

    /**
     * Create an instance of {@link NAMEPARTICIPANT }
     * 
     */
    public NAMEPARTICIPANT createNAMEPARTICIPANT() {
        return new NAMEPARTICIPANT();
    }

    /**
     * Create an instance of {@link E1VDEWRFF2 }
     * 
     */
    public E1VDEWRFF2 createE1VDEWRFF2() {
        return new E1VDEWRFF2();
    }

    /**
     * Create an instance of {@link REFERENCEQUALIFIER }
     * 
     */
    public REFERENCEQUALIFIER createREFERENCEQUALIFIER() {
        return new REFERENCEQUALIFIER();
    }

    /**
     * Create an instance of {@link REFERENCENUMBER }
     * 
     */
    public REFERENCENUMBER createREFERENCENUMBER() {
        return new REFERENCENUMBER();
    }

    /**
     * Create an instance of {@link LINENUMBER }
     * 
     */
    public LINENUMBER createLINENUMBER() {
        return new LINENUMBER();
    }

    /**
     * Create an instance of {@link VERSIONNUMBER }
     * 
     */
    public VERSIONNUMBER createVERSIONNUMBER() {
        return new VERSIONNUMBER();
    }

    /**
     * Create an instance of {@link E1VDEWSEQ2 }
     * 
     */
    public E1VDEWSEQ2 createE1VDEWSEQ2() {
        return new E1VDEWSEQ2();
    }

    /**
     * Create an instance of {@link SEQUINFOSSEQUENCENR }
     * 
     */
    public SEQUINFOSSEQUENCENR createSEQUINFOSSEQUENCENR() {
        return new SEQUINFOSSEQUENCENR();
    }

    /**
     * Create an instance of {@link SEQUINFOSSEQUENCENRCODE }
     * 
     */
    public SEQUINFOSSEQUENCENRCODE createSEQUINFOSSEQUENCENRCODE() {
        return new SEQUINFOSSEQUENCENRCODE();
    }

    /**
     * Create an instance of {@link SEQUINFOSCODELIST }
     * 
     */
    public SEQUINFOSCODELIST createSEQUINFOSCODELIST() {
        return new SEQUINFOSCODELIST();
    }

    /**
     * Create an instance of {@link SEQUINFOSAGENCY }
     * 
     */
    public SEQUINFOSAGENCY createSEQUINFOSAGENCY() {
        return new SEQUINFOSAGENCY();
    }

    /**
     * Create an instance of {@link E1VDEWPIA2 }
     * 
     */
    public E1VDEWPIA2 createE1VDEWPIA2() {
        return new E1VDEWPIA2();
    }

    /**
     * Create an instance of {@link ITEMNUMBER1 }
     * 
     */
    public ITEMNUMBER1 createITEMNUMBER1() {
        return new ITEMNUMBER1();
    }

    /**
     * Create an instance of {@link ITEMNUMBERTYPE1 }
     * 
     */
    public ITEMNUMBERTYPE1 createITEMNUMBERTYPE1() {
        return new ITEMNUMBERTYPE1();
    }

    /**
     * Create an instance of {@link ITEMNUMBER2 }
     * 
     */
    public ITEMNUMBER2 createITEMNUMBER2() {
        return new ITEMNUMBER2();
    }

    /**
     * Create an instance of {@link ITEMNUMBERTYPE2 }
     * 
     */
    public ITEMNUMBERTYPE2 createITEMNUMBERTYPE2() {
        return new ITEMNUMBERTYPE2();
    }

    /**
     * Create an instance of {@link ITEMNUMBER3 }
     * 
     */
    public ITEMNUMBER3 createITEMNUMBER3() {
        return new ITEMNUMBER3();
    }

    /**
     * Create an instance of {@link ITEMNUMBERTYPE3 }
     * 
     */
    public ITEMNUMBERTYPE3 createITEMNUMBERTYPE3() {
        return new ITEMNUMBERTYPE3();
    }

    /**
     * Create an instance of {@link ITEMNUMBER4 }
     * 
     */
    public ITEMNUMBER4 createITEMNUMBER4() {
        return new ITEMNUMBER4();
    }

    /**
     * Create an instance of {@link ITEMNUMBERTYPE4 }
     * 
     */
    public ITEMNUMBERTYPE4 createITEMNUMBERTYPE4() {
        return new ITEMNUMBERTYPE4();
    }

    /**
     * Create an instance of {@link ITEMNUMBER5 }
     * 
     */
    public ITEMNUMBER5 createITEMNUMBER5() {
        return new ITEMNUMBER5();
    }

    /**
     * Create an instance of {@link ITEMNUMBERTYPE5 }
     * 
     */
    public ITEMNUMBERTYPE5 createITEMNUMBERTYPE5() {
        return new ITEMNUMBERTYPE5();
    }

    /**
     * Create an instance of {@link E1VDEWQTY }
     * 
     */
    public E1VDEWQTY createE1VDEWQTY() {
        return new E1VDEWQTY();
    }

    /**
     * Create an instance of {@link QUANTITYQUALIFIER }
     * 
     */
    public QUANTITYQUALIFIER createQUANTITYQUALIFIER() {
        return new QUANTITYQUALIFIER();
    }

    /**
     * Create an instance of {@link QUANTITY }
     * 
     */
    public QUANTITY createQUANTITY() {
        return new QUANTITY();
    }

    /**
     * Create an instance of {@link MEASUREUNITQUALIFIER }
     * 
     */
    public MEASUREUNITQUALIFIER createMEASUREUNITQUALIFIER() {
        return new MEASUREUNITQUALIFIER();
    }

    /**
     * Create an instance of {@link E1VDEWMOA6 }
     * 
     */
    public E1VDEWMOA6 createE1VDEWMOA6() {
        return new E1VDEWMOA6();
    }

    /**
     * Create an instance of {@link MONETARYAMOUNTTYPE }
     * 
     */
    public MONETARYAMOUNTTYPE createMONETARYAMOUNTTYPE() {
        return new MONETARYAMOUNTTYPE();
    }

    /**
     * Create an instance of {@link MONETARYAMOUNTVALUE }
     * 
     */
    public MONETARYAMOUNTVALUE createMONETARYAMOUNTVALUE() {
        return new MONETARYAMOUNTVALUE();
    }

    /**
     * Create an instance of {@link STATUS }
     * 
     */
    public STATUS createSTATUS() {
        return new STATUS();
    }

    /**
     * Create an instance of {@link E1VDEWRFF3 }
     * 
     */
    public E1VDEWRFF3 createE1VDEWRFF3() {
        return new E1VDEWRFF3();
    }

    /**
     * Create an instance of {@link E1VDEWNAD4 }
     * 
     */
    public E1VDEWNAD4 createE1VDEWNAD4() {
        return new E1VDEWNAD4();
    }

    /**
     * Create an instance of {@link PARTNER }
     * 
     */
    public PARTNER createPARTNER() {
        return new PARTNER();
    }

    /**
     * Create an instance of {@link NAMEADDRESS1 }
     * 
     */
    public NAMEADDRESS1 createNAMEADDRESS1() {
        return new NAMEADDRESS1();
    }

    /**
     * Create an instance of {@link NAMEADDRESS2 }
     * 
     */
    public NAMEADDRESS2 createNAMEADDRESS2() {
        return new NAMEADDRESS2();
    }

    /**
     * Create an instance of {@link NAMEADDRESS3 }
     * 
     */
    public NAMEADDRESS3 createNAMEADDRESS3() {
        return new NAMEADDRESS3();
    }

    /**
     * Create an instance of {@link NAMEADDRESS4 }
     * 
     */
    public NAMEADDRESS4 createNAMEADDRESS4() {
        return new NAMEADDRESS4();
    }

    /**
     * Create an instance of {@link NAMEADDRESS5 }
     * 
     */
    public NAMEADDRESS5 createNAMEADDRESS5() {
        return new NAMEADDRESS5();
    }

    /**
     * Create an instance of {@link PARTNERNAME1 }
     * 
     */
    public PARTNERNAME1 createPARTNERNAME1() {
        return new PARTNERNAME1();
    }

    /**
     * Create an instance of {@link PARTNERNAME2 }
     * 
     */
    public PARTNERNAME2 createPARTNERNAME2() {
        return new PARTNERNAME2();
    }

    /**
     * Create an instance of {@link PARTNERNAME3 }
     * 
     */
    public PARTNERNAME3 createPARTNERNAME3() {
        return new PARTNERNAME3();
    }

    /**
     * Create an instance of {@link PARTNERNAME4 }
     * 
     */
    public PARTNERNAME4 createPARTNERNAME4() {
        return new PARTNERNAME4();
    }

    /**
     * Create an instance of {@link PARTNERNAME5 }
     * 
     */
    public PARTNERNAME5 createPARTNERNAME5() {
        return new PARTNERNAME5();
    }

    /**
     * Create an instance of {@link PARTNERFORMAT }
     * 
     */
    public PARTNERFORMAT createPARTNERFORMAT() {
        return new PARTNERFORMAT();
    }

    /**
     * Create an instance of {@link STREET1 }
     * 
     */
    public STREET1 createSTREET1() {
        return new STREET1();
    }

    /**
     * Create an instance of {@link STREET2 }
     * 
     */
    public STREET2 createSTREET2() {
        return new STREET2();
    }

    /**
     * Create an instance of {@link STREET3 }
     * 
     */
    public STREET3 createSTREET3() {
        return new STREET3();
    }

    /**
     * Create an instance of {@link STREET4 }
     * 
     */
    public STREET4 createSTREET4() {
        return new STREET4();
    }

    /**
     * Create an instance of {@link REGION }
     * 
     */
    public REGION createREGION() {
        return new REGION();
    }

    /**
     * Create an instance of {@link ZIPCODE }
     * 
     */
    public ZIPCODE createZIPCODE() {
        return new ZIPCODE();
    }

    /**
     * Create an instance of {@link E1VDEWRFF4 }
     * 
     */
    public E1VDEWRFF4 createE1VDEWRFF4() {
        return new E1VDEWRFF4();
    }

    /**
     * Create an instance of {@link E1VDEWNAD1 }
     * 
     */
    public E1VDEWNAD1 createE1VDEWNAD1() {
        return new E1VDEWNAD1();
    }

    /**
     * Create an instance of {@link E1VDEWRFF1 }
     * 
     */
    public E1VDEWRFF1 createE1VDEWRFF1() {
        return new E1VDEWRFF1();
    }

    /**
     * Create an instance of {@link E1VDEWUNH }
     * 
     */
    public E1VDEWUNH createE1VDEWUNH() {
        return new E1VDEWUNH();
    }

    /**
     * Create an instance of {@link IDENTIFIER }
     * 
     */
    public IDENTIFIER createIDENTIFIER() {
        return new IDENTIFIER();
    }

    /**
     * Create an instance of {@link RELEASENUMBER }
     * 
     */
    public RELEASENUMBER createRELEASENUMBER() {
        return new RELEASENUMBER();
    }

    /**
     * Create an instance of {@link TRANSFERNUMBER }
     * 
     */
    public TRANSFERNUMBER createTRANSFERNUMBER() {
        return new TRANSFERNUMBER();
    }

    /**
     * Create an instance of {@link INDICATOR }
     * 
     */
    public INDICATOR createINDICATOR() {
        return new INDICATOR();
    }

    /**
     * Create an instance of {@link E1VDEWUNT }
     * 
     */
    public E1VDEWUNT createE1VDEWUNT() {
        return new E1VDEWUNT();
    }

    /**
     * Create an instance of {@link NUMSEG }
     * 
     */
    public NUMSEG createNUMSEG() {
        return new NUMSEG();
    }

    /**
     * Create an instance of {@link REFNUM }
     * 
     */
    public REFNUM createREFNUM() {
        return new REFNUM();
    }

    /**
     * Create an instance of {@link EDIDC40 }
     * 
     */
    public EDIDC40 createEDIDC40() {
        return new EDIDC40();
    }

    /**
     * Create an instance of {@link TABNAM }
     * 
     */
    public TABNAM createTABNAM() {
        return new TABNAM();
    }

    /**
     * Create an instance of {@link MANDT }
     * 
     */
    public MANDT createMANDT() {
        return new MANDT();
    }

    /**
     * Create an instance of {@link OUTMOD }
     * 
     */
    public OUTMOD createOUTMOD() {
        return new OUTMOD();
    }

    /**
     * Create an instance of {@link EXPRSS }
     * 
     */
    public EXPRSS createEXPRSS() {
        return new EXPRSS();
    }

    /**
     * Create an instance of {@link TEST }
     * 
     */
    public TEST createTEST() {
        return new TEST();
    }

    /**
     * Create an instance of {@link IDOCTYP }
     * 
     */
    public IDOCTYP createIDOCTYP() {
        return new IDOCTYP();
    }

    /**
     * Create an instance of {@link MESTYP }
     * 
     */
    public MESTYP createMESTYP() {
        return new MESTYP();
    }

    /**
     * Create an instance of {@link MESCOD }
     * 
     */
    public MESCOD createMESCOD() {
        return new MESCOD();
    }

    /**
     * Create an instance of {@link MESFCT }
     * 
     */
    public MESFCT createMESFCT() {
        return new MESFCT();
    }

    /**
     * Create an instance of {@link STD }
     * 
     */
    public STD createSTD() {
        return new STD();
    }

    /**
     * Create an instance of {@link STDVRS }
     * 
     */
    public STDVRS createSTDVRS() {
        return new STDVRS();
    }

    /**
     * Create an instance of {@link STDMES }
     * 
     */
    public STDMES createSTDMES() {
        return new STDMES();
    }

    /**
     * Create an instance of {@link SNDPOR }
     * 
     */
    public SNDPOR createSNDPOR() {
        return new SNDPOR();
    }

    /**
     * Create an instance of {@link SNDPRT }
     * 
     */
    public SNDPRT createSNDPRT() {
        return new SNDPRT();
    }

    /**
     * Create an instance of {@link SNDPFC }
     * 
     */
    public SNDPFC createSNDPFC() {
        return new SNDPFC();
    }

    /**
     * Create an instance of {@link SNDPRN }
     * 
     */
    public SNDPRN createSNDPRN() {
        return new SNDPRN();
    }

    /**
     * Create an instance of {@link SNDSAD }
     * 
     */
    public SNDSAD createSNDSAD() {
        return new SNDSAD();
    }

    /**
     * Create an instance of {@link SNDLAD }
     * 
     */
    public SNDLAD createSNDLAD() {
        return new SNDLAD();
    }

    /**
     * Create an instance of {@link RCVPOR }
     * 
     */
    public RCVPOR createRCVPOR() {
        return new RCVPOR();
    }

    /**
     * Create an instance of {@link RCVPRT }
     * 
     */
    public RCVPRT createRCVPRT() {
        return new RCVPRT();
    }

    /**
     * Create an instance of {@link RCVPFC }
     * 
     */
    public RCVPFC createRCVPFC() {
        return new RCVPFC();
    }

    /**
     * Create an instance of {@link RCVPRN }
     * 
     */
    public RCVPRN createRCVPRN() {
        return new RCVPRN();
    }

    /**
     * Create an instance of {@link RCVSAD }
     * 
     */
    public RCVSAD createRCVSAD() {
        return new RCVSAD();
    }

    /**
     * Create an instance of {@link RCVLAD }
     * 
     */
    public RCVLAD createRCVLAD() {
        return new RCVLAD();
    }

    /**
     * Create an instance of {@link REFINT }
     * 
     */
    public REFINT createREFINT() {
        return new REFINT();
    }

    /**
     * Create an instance of {@link REFGRP }
     * 
     */
    public REFGRP createREFGRP() {
        return new REFGRP();
    }

    /**
     * Create an instance of {@link REFMES }
     * 
     */
    public REFMES createREFMES() {
        return new REFMES();
    }

    /**
     * Create an instance of {@link SERIAL }
     * 
     */
    public SERIAL createSERIAL() {
        return new SERIAL();
    }

    /**
     * Create an instance of {@link IDOC }
     * 
     */
    public IDOC createIDOC() {
        return new IDOC();
    }

    /**
     * Create an instance of {@link ISUVDEWUTILMDV30 }
     * 
     */
    public ISUVDEWUTILMDV30 createISUVDEWUTILMDV30() {
        return new ISUVDEWUTILMDV30();
    }

}
